#!/usr/bin/env -S deno run --no-lock --allow-read --allow-write --allow-run --allow-env
//
// A wizard walks a human through a manual procedure, step by step.
// Generated by the /wizard skill.
//
// Everything above the "STAGES" marker is the wizard library: do not hand-edit
// it. Author each stage below the marker as one named Pipeline step.
//
// Copy this file to the target path, replace the example steps, and run:
//   deno check <wizard>.ts
//   deno run --no-lock --allow-read --allow-write --allow-run --allow-env <wizard>.ts
//
// Self contained: pinned npm: imports resolve from the Deno cache.
// --no-lock keeps Deno from writing a deno.lock file. Nothing touches
// package.json, pnpm-lock.yaml, or node_modules.

import { $ } from "npm:zx@8.8.5";
import { MepCLI, Pipeline } from "npm:mepcli@1.4.0";

// ── Wizard library: same UX in every wizard. Do not hand-edit. ──

const USE_COLOR = Deno.stdout.isTerminal() && !Deno.env.get("NO_COLOR");
const BOLD = USE_COLOR ? "\x1b[1m" : "";
const DIM = USE_COLOR ? "\x1b[2m" : "";
const RESET = USE_COLOR ? "\x1b[0m" : "";
const BLUE = USE_COLOR ? "\x1b[34m" : "";
const GREEN = USE_COLOR ? "\x1b[32m" : "";
const YELLOW = USE_COLOR ? "\x1b[33m" : "";

// Author sets this below the STAGES marker to match the step count.
let TOTAL_STAGES = 0;

const ENV_FILE = Deno.env.get("ENV_FILE") ?? ".env";
const WRITTEN_ENV: string[] = [];
const WRITTEN_SECRET: string[] = [];
const SKIPPED: string[] = [];

function progressPath(): string {
  return Deno.env.get("WIZARD_PROGRESS") ?? "./wizard-progress.jsonl";
}

async function appendEvent(event: unknown): Promise<void> {
  try {
    await Deno.writeTextFile(progressPath(), JSON.stringify(event) + "\n", { append: true });
  } catch {
    // Progress must never break the wizard.
  }
}

function clear(): void {
  if (Deno.stdout.isTerminal()) console.clear();
}

// createWizard returns a Pipeline whose hooks clear the screen, print the
// stage counter, and append one JSONL event per step start and completion.
// The counter tracks executed steps, so conditional steps never skew it.
export function createWizard<Ctx extends Record<string, unknown>>(): Pipeline<Ctx> {
  let done = 0;
  return new Pipeline<Ctx>({
    onStepStart: async (meta) => {
      clear();
      const n = done + 1;
      console.log(`\n${BOLD}${BLUE}▸ Stage ${n}/${TOTAL_STAGES} · ${meta.name ?? "step"}${RESET}`);
      await appendEvent({
        type: "stage",
        index: n,
        name: meta.name,
        time: new Date().toISOString(),
      });
    },
    onStepComplete: async (meta) => {
      done += 1;
      await appendEvent({
        type: "stage-complete",
        index: meta.index + 1,
        name: meta.name,
        time: new Date().toISOString(),
      });
    },
  });
}

// banner shows the opening frame: what this wizard does.
// A no answer stops the run before any stage executes.
export async function banner(title: string): Promise<void> {
  clear();
  console.log(`\n${BOLD}${BLUE}  ${title}${RESET}`);
  console.log(`${DIM}  ${TOTAL_STAGES} stages${RESET}\n`);
  console.log(`${DIM}  You drive the browser; this wizard tells you exactly what to do and`);
  console.log(`  captures the values you copy back.${RESET}`);
  const ready = await confirm("Ready to start?");
  if (!ready) {
    say("Stopped. Run the wizard again when ready.");
    Deno.exit(0);
  }
}

export function say(text: string): void {
  console.log(`  ${text}`);
}
export function step(text: string): void {
  console.log(`  ${BLUE}•${RESET} ${text}`);
}
export function note(text: string): void {
  console.log(`  ${DIM}${text}${RESET}`);
}
export function warn(text: string): void {
  console.log(`  ${YELLOW}⚠ ${text}${RESET}`);
}

// open_url opens a URL in the human's browser, cross-platform incl. WSL.
export async function open_url(url: string): Promise<void> {
  console.log(`  ${GREEN}↗ opening${RESET} ${url}`);
  const attempts: Array<() => Promise<unknown>> = [
    () => $`wslview ${url}`,
    () => $`explorer.exe ${url}`,
    () => $`xdg-open ${url}`,
    () => $`open ${url}`,
  ];
  for (const run of attempts) {
    try {
      await run();
      return;
    } catch {
      // Try the next opener.
    }
  }
  warn(`couldn't open a browser, so visit it manually: ${url}`);
}

// confirm asks a y/N gate; resolves true on yes.
export async function confirm(question: string): Promise<boolean> {
  return await MepCLI.confirm({ message: question });
}

function existing(key: string): string | null {
  let text: string;
  try {
    text = Deno.readTextFileSync(ENV_FILE);
  } catch {
    return null;
  }
  let found: string | null = null;
  for (const line of text.split("\n")) {
    if (line.startsWith(`${key}=`)) found = line.slice(key.length + 1);
  }
  return found;
}

function keptCurrent(value: string, current: string | null): string {
  if (value.trim() === "" && current) return current;
  return value;
}

// ask reads a visible value; Enter keeps the saved .env value on re-runs.
export async function ask(key: string, promptText: string): Promise<string> {
  const current = existing(key);
  const value = await MepCLI.text({
    message: `${promptText}${current ? " [Enter keeps current]" : ""}`,
    initial: current ?? undefined,
  });
  return keptCurrent(value, current);
}

// ask_secret is like ask, but input stays hidden.
export async function ask_secret(key: string, promptText: string): Promise<string> {
  const current = existing(key);
  const value = await MepCLI.secret({
    message: `${promptText}${current ? " [Enter keeps current]" : ""}`,
    initial: current ?? undefined,
  });
  return keptCurrent(value, current);
}

async function ghReady(): Promise<boolean> {
  try {
    await $`gh auth status`;
    return true;
  } catch {
    return false;
  }
}

// write_env upserts KEY=VALUE into ENV_FILE. Idempotent.
export async function write_env(key: string, value: string): Promise<void> {
  let lines: string[] = [];
  try {
    lines = Deno.readTextFileSync(ENV_FILE).split("\n");
  } catch {
    lines = [];
  }
  const kept = lines.filter((line) => !line.startsWith(`${key}=`));
  const trimmed = kept.join("\n").replace(/\n+$/, "");
  const next = trimmed ? `${trimmed}\n${key}=${value}\n` : `${key}=${value}\n`;
  await Deno.writeTextFile(ENV_FILE, next);
  WRITTEN_ENV.push(key);
  console.log(`  ${GREEN}✓ wrote${RESET} ${key} → ${ENV_FILE}`);
}

// set_secret sets a GitHub Actions repo secret via gh, else records a skip.
export async function set_secret(name: string, value: string): Promise<void> {
  if (await ghReady()) {
    try {
      await $`gh secret set ${name} --body ${value}`;
      WRITTEN_SECRET.push(name);
      console.log(`  ${GREEN}✓ set${RESET} GitHub secret ${name}`);
      return;
    } catch {
      // Fall through to the skip warning.
    }
  }
  SKIPPED.push(`GitHub secret ${name} (set it manually: gh secret set ${name})`);
  warn(`skipped GitHub secret ${name}: gh not ready; set it later`);
}

// set_var sets a GitHub Actions repo variable (non-secret), else skips.
export async function set_var(name: string, value: string): Promise<void> {
  if (await ghReady()) {
    try {
      await $`gh variable set ${name} --body ${value}`;
      console.log(`  ${GREEN}✓ set${RESET} GitHub variable ${name}`);
      return;
    } catch {
      // Fall through to the skip warning.
    }
  }
  SKIPPED.push(`GitHub variable ${name}`);
  warn(`skipped GitHub variable ${name}, gh not ready; set it later`);
}

// finish shows the closing summary and appends the done event.
export async function finish(): Promise<void> {
  console.log(`\n${BOLD}${GREEN}  ✓ Setup complete${RESET}`);
  if (WRITTEN_ENV.length)
    note(`wrote ${WRITTEN_ENV.length} value(s) to ${ENV_FILE}: ${WRITTEN_ENV.join(" ")}`);
  if (WRITTEN_SECRET.length)
    note(`set ${WRITTEN_SECRET.length} GitHub secret(s): ${WRITTEN_SECRET.join(" ")}`);
  if (SKIPPED.length) {
    console.log("");
    warn("still to do by hand:");
    for (const s of SKIPPED) note(`  - ${s}`);
  }
  console.log("");
  await appendEvent({
    type: "done",
    time: new Date().toISOString(),
    envKeys: WRITTEN_ENV,
    secrets: WRITTEN_SECRET,
    skipped: SKIPPED,
  });
}

// STAGES: AGENT EDIT BELOW. One Pipeline step per stage. Set TOTAL_STAGES to match.
// zx escape hatch: use $`cmd args` for shell, e.g. await $`gh auth status`.
TOTAL_STAGES = 2;

await banner("Stripe setup");
// AGENT EDIT BELOW: replace example steps with real steps.
await createWizard<{ "publishable-key": string; "secret-key": string }>()
  .step(
    "publishable-key",
    async () => {
      say("Grab test keys for local dev + CI.");
      await open_url("https://dashboard.stripe.com/test/apikeys");
      step("Copy the Publishable key (starts pk_test_).");
      const v = await ask("STRIPE_PUBLISHABLE_KEY", "Paste the publishable key:");
      await write_env("STRIPE_PUBLISHABLE_KEY", v);
      return v;
    },
    { validate: (v) => (String(v).trim() ? true : "Paste the publishable key.") },
  )
  .step(
    "secret-key",
    async () => {
      step("Click 'Reveal test key', then copy it.");
      const v = await ask_secret("STRIPE_SECRET_KEY", "Paste the secret key:");
      await write_env("STRIPE_SECRET_KEY", v);
      await set_secret("STRIPE_SECRET_KEY", v);
      return v;
    },
    { validate: (v) => (String(v).trim() ? true : "Paste the secret key.") },
  )
  .run();
await finish();
