#!/usr/bin/env bash
# dsh personal bundle installer — idempotent.
#
# Usage:  clone the dotfiles-ai repo, cd into it, run ./sync.sh
#   ./sync.sh                          # installs into $DSH_HOME (default ~/.dsh)
#   DSH_HOME=/path/to/home ./sync.sh
#   AIDOS_PLUGIN_SPEC=github:you/aidos ./sync.sh   # override the aidos git spec
#                                                  # always use the full git commit sha
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$HERE"
export DSH_HOME="${DSH_HOME:-$HOME/.dsh}"
AIDOS_PLUGIN_SPEC="${AIDOS_PLUGIN_SPEC:-github:xyzshantaram/aidos#61155267d13b4823e8c5a12e0f52c4d94c3e817b}"

step_install_deps() {
	(cd "$REPO" && pnpm install)
}

step_build_plugins() {
	(cd "$HERE" && node build.mjs)
}

step_sync_skills() {
	mkdir -p "$DSH_HOME/skills"
	cp -r "$HERE/skills/." "$DSH_HOME/skills/"
}

step_sync_agents_md() {
	cp "$HERE/home/AGENTS.md" "$DSH_HOME/AGENTS.md"
}

step_sync_better_edit_guidance() {
	mkdir -p "$DSH_HOME/plugins/dsh-better-edit"
	cp -r "$HERE/home/plugins/dsh-better-edit/." "$DSH_HOME/plugins/dsh-better-edit/"
}

step_sync_guard_rules() {
	mkdir -p "$DSH_HOME/plugins/guards"
	cp -r "$HERE/guards/." "$DSH_HOME/plugins/guards/"
}

step_write_web_patch() {
	patch_dir="$DSH_HOME/profiles/web"
	mkdir -p "$patch_dir"
	cat > "$patch_dir/cordis.patch.yml" <<PATCH
# Auto-generated by $HERE/sync.sh. Do not hand-edit; re-run the script instead.
# Personal bundle host-plane rows: these apply to EVERY session regardless of
# preset — the MCP servers, the bash guard (rules read live from
# $DSH_HOME/plugins/guards/*.json), the manifest guard, the package tool,
# and the profile-routed see vision helper. The plugin files resolve their
# @deepseek-ai/* imports against the host base (dsh install node_modules);
# unbash + the walker are bundled inside each plugin file.
- insert:
    - id: log-exporter
      name: $HERE/plugins/log-exporter.js
    - id: mcp-nostrbook
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: nostrbook
        transport: stdio
        command: npx
        args: ['-y', '@nostrbook/mcp@latest']
    - id: mcp-gitlab
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: gitlab
        transport: stdio
        command: glab
        args: ['mcp', 'serve']
    - id: mcp-swiggy-food
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: swiggy-food
        transport: streamable-http
        url: https://mcp.swiggy.com/food
    - id: mcp-swiggy-instamart
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: swiggy-instamart
        transport: streamable-http
        url: https://mcp.swiggy.com/im
    - id: bash-guard
      name: $HERE/plugins/bash-guard.js
      config:
        guardsDir: $DSH_HOME/plugins/guards
    - id: manifest-guard
      name: $HERE/plugins/manifest-guard.js
    - id: package-tool
      name: $HERE/plugins/package-tool.js
    - id: skill-gate
      name: $HERE/plugins/skill-gate.js
    - id: see
      name: $HERE/plugins/see.js
    - id: tmp-dsh-shared
      name: $HERE/plugins/tmp-dsh-shared.js
    - id: grant
      name: $HERE/plugins/grant.js

    - id: ask-interrupt
      name: $HERE/plugins/ask-interrupt.js


    - id: profiles
      name: $HERE/plugins/profiles.js
    - id: resume-command
      name: $HERE/plugins/resume.js
    # The cordis_* tools, gated behind the two cordis skills via skill-gate.
    - id: tool-cordis
      name: '@deepseek-ai/dsh-tool-cordis'
    - id: compaction-instant
      name: '@deepseek-ai/dsh-compaction-basic'
    - id: tool-recall
      name: '@deepseek-ai/dsh-compaction-basic/tool'
    - id: command-recall
      name: '@deepseek-ai/dsh-compaction-basic/command'
    - id: ui-better-mobile
      name: dsh-plugin-better-mobile-ui
    # Vendored llm-pi-ai fork mounts as its own row; the builtin is disabled below.
    - id: llm-pi-ai-affinity
      name: '@deepseek-ai/dsh-llm-pi-ai'


# Override the builtin llm-pi-ai row: the vendored fork (linked into the
# web profile under the same package name) is the only pi-ai adapter
# registrar. Disabling the builtin avoids duplicate adapter registration;
# the fork mounts as llm-pi-ai-affinity in the insert list above.
- id: llm-pi-ai
  disabled: true

# Config override for the self-mounting dsh-remote plugin (the plugin
# install step pins our fork). The plugin creates the remote row from its
# own bundle patch, so this MUST be a top-level override row, NOT a child
# of the insert list above: an insert row with the same id kills boot with
# "duplicate loader entry id: remote".
#
# applyEntryPatches assigns each override key WHOLESALE (target[key] = value,
# dsh-app-boot/lib/index.js). It does not deep-merge, so the block below must
# repeat every default from the plugin's own cordis.patch.yml. Only two values
# differ from those defaults:
#   session.secure: the proxy terminates TLS, so the cookie may carry Secure.
#   debug: registers POST /auth/trace, which writes client trace lines to the
#     server journal. Keep it false unless you debug a remote-mode fault. The
#     client half only ships traces when the page URL also carries ?dshTrace=1.
- id: remote
  config:
    enabled: true
    debug: true
    accounts: []
    secret: ''
    session:
      cookieName: dsh_session
      ttlSeconds: 604800
      secure: true
      sameSite: lax
    enforceRoles: true
    rateLimit:
      maxAttempts: 5
      windowMs: 900000
    files:
      roots:
        - /tmp/dsh

PATCH
}

step_install_plugins() {
	# Idempotent: a repeat `dsh plugin add` of an installed spec converges
	# instead of duplicating a row.
	if command -v dsh >/dev/null 2>&1; then
		# One install helper: print the plugin name, keep pnpm quiet, and
		# surface only warnings and errors (or the full output on failure).
		pnpm_ins() {
			local spec="$1" name
			name="$(printf '%s' "$spec" | sed -E 's#.*github.com/[^/]+/([^/#]+)/archive.*#\1#; s/#[^/]*$//; s#.*[/:]##')"
			name="${name%%@*}"
			echo "  installing ${name:-$spec}"
			local out rc
			out="$(dsh plugin --profile web add "$spec" 2>&1)"
			rc=$?
			if [ "$rc" -ne 0 ]; then printf '%s\n' "$out"; return "$rc"; fi
			# pnpm's peer-dependency notice fires on nearly every install in
			# this bundle (each plugin declares its own dsh peer range) and
			# carries no actionable info here; drop only that one line, keep
			# every other warn/error.
			printf '%s\n' "$out" | rg -i 'warn|error' | rg -v -i 'peer dependenc' || true
		}
		pnpm_ins "github:sunshaobei/dsh-input-history#9b5b7a494a5c"
		pnpm_ins "github:omdsh-dev/dsh-tool-calculator#05090e946113721c5295518cc20e74f427022c55"
		pnpm_ins "github:omdsh-dev/dsh-tool-diff#d4afd6e2de0b411151fefc60adebd0973373ec10"
		# The four tools the `util` skill gates (ticket E4). Installed as
		# separate repos, NOT through the omdsh-dev/dsh-toolkit monorepo:
		# that collection also registers calculator and diff, which are
		# already installed above and would be double-registered.
		pnpm_ins "github:omdsh-dev/dsh-tool-time#8b7a2137f516f9d9179663f5aa58928034c90377"
		pnpm_ins "github:omdsh-dev/dsh-tool-regex#5afda86cd6862a25f6684056b378c330a5aa86b3"
		pnpm_ins "github:omdsh-dev/dsh-tool-markdown#267871b115c49c5cde072d05d0d2cef6982ae8f8"
		pnpm_ins "github:omdsh-dev/dsh-tool-encoding#dbf829b5a755d27ed64a146a4bfa50a62f985f6c"
		pnpm_ins "https://github.com/omdsh-dev/dsh-at-file/archive/refs/tags/v0.6.7.tar.gz"
		# dsh plugin --profile web add dsh-worktree
		pnpm_ins "github:Tieboyh/dsh-session-search#82990a0e9804"
		# Remote-access auth: dsh serves settings RPCs loopback-only, so every
		# proxied browser gets inert settings scopes without this plugin.
		# Self-mounts via its own bundle patch; the patch step adds the
		# config row (secure cookie, debug trace). Pinned to OUR fork
		# (github.com/xyzshantaram/dsh-remote); upgrade = bump the pin.
		pnpm_ins "github:xyzshantaram/dsh-remote#0c9e708c2b5c"
		# Streaming markdown renderer (Mermaid, KaTeX, Shiki); client-only.
		pnpm_ins "dsh-better-markdown@0.1.2"
		# Paste-to-path: pasted files land under <workspace>/.dsh/pastes/ and
		# the composer carries a PATH reference. Replaced dsh-paste-input.
		pnpm_ins "github:Johnny-xuan/dsh-paste-to-path#d68fb104ca25a663ba3912bb17f8c2ab32d60e37"
		pnpm_ins "github:davidgereb/dsh-plugin-better-mobile-ui#16e21548315866b50d5f3f64b91a70f24f3318ba"

		pnpm_ins "$HERE/plugins/session-archive"
		pnpm_ins "$HERE/plugins/subscriptions"
		pnpm_ins "$HERE/plugins/tool-render"
		pnpm_ins "$HERE/plugins/profiles-client"
		pnpm_ins "$HERE/plugins/approval-comment"
		pnpm_ins "$HERE/plugins/llm-pi-ai"
	else
		echo "WARNING: dsh not on PATH; skipping third-party plugin installs."
		echo "         Re-run './sync.sh' from a shell where dsh is installed."
	fi
}

step_report_extra_plugins() {
	# Print removal commands for plugins installed on the web profile that are
	# NOT part of this bundle's set. sync.sh only ever ADDS plugins, so a
	# plugin dropped from the set above stays installed until removed; this
	# step surfaces the exact command. It prints only, never removes.
	if ! command -v dsh >/dev/null 2>&1; then
		echo "WARNING: dsh not on PATH; skipping extra-plugin check."
		return 0
	fi
	# Exact package names this bundle installs (the pnpm_ins specs above plus
	# aidos), and the profile's own base deps that are not extras. Keep this
	# in sync with the pnpm_ins list when you add or drop a plugin.
	# Keep in sync with pnpm_ins specs above; see step_install_plugins.
	local expected=(
		"@deepseek-ai/dsh-tool-calculator"
		"@deepseek-ai/dsh-tool-diff"
		"@deepseek-ai/dsh-tool-encoding"
		"@deepseek-ai/dsh-tool-markdown"
		"@deepseek-ai/dsh-tool-regex"
		"@deepseek-ai/dsh-tool-time"
		"@deepseek-ai/dsh-compaction-basic"
		"@deepseek-ai/dsh-llm-pi-ai"
		"@dsh-external/dsh-session-search"
		"@xgone/dsh-remote"
		"aidos"
		"approval-comment"
		"dsh-at-file"
		"dsh-better-markdown"
		"dsh-input-history"
		"dsh-paste-to-path"
		"profiles-client"
		"session-archive"
		"subscriptions"
		"tool-render"

		"dsh-plugin-better-mobile-ui"
	)
	local base=(
		"@deepseek-ai/dsh-client-ui-attachment"
		"@deepseek-ai/dsh-client-web-react"
		"dsh-better-edit"
	)
	local installed extra=0 name
	installed="$(dsh plugin --profile web list --depth 0 --json 2>/dev/null | python3 -c '
import json, sys
try:
    data = json.load(sys.stdin)
except Exception:
    sys.exit(0)
proj = data[0] if isinstance(data, list) and data else data
if not isinstance(proj, dict):
    sys.exit(0)
for key in (proj.get("dependencies") or {}):
    print(key)
')"
	if [ -z "$installed" ]; then
		echo "  (could not read the installed plugin list; skipping extra check)"
		return 0
	fi
	for name in $installed; do
		case " ${expected[*]} ${base[*]} " in
			*" $name "*) ;;
			*)
				echo "  extra plugin: $name"
				echo "    dsh plugin --profile web remove $name"
				extra=1
				;;
		esac
	done
	if [ "$extra" -eq 0 ]; then
		echo "  no extra plugins."
	else
		echo "  (informational only — sync continues despite extra plugins)" >&2
	fi
	return 0
}

step_allow_aidos_build() {
	# pnpm refuses to run a package's install/build scripts unless its exact
	# resolved tarball URL is listed under `allowBuilds` in the web profile's
	# pnpm-workspace.yaml. aidos needs its postinstall, so add the entry for the
	# CURRENT pin (AIDOS_PLUGIN_SPEC) idempotently. The pin changes per bump, so
	# we reconstruct the codeload tarball URL the same way pnpm does from the
	# github spec (owner/repo#ref -> tarball, name = repo basename).
	local ws="$DSH_HOME/profiles/web/pnpm-workspace.yaml"
	local spec="${AIDOS_PLUGIN_SPEC}"
	local path ref name tarball key
	path="${spec#github:}"
	ref="${spec##*#}"
	path="${path%#*}"
	name="$(basename "$path")"
	tarball="https://codeload.github.com/${path}/tar.gz/${ref}"
	key="${name}@${tarball}"
	mkdir -p "$(dirname "$ws")"
	touch "$ws"
	if ! grep -qxF "  ${key}: true" "$ws"; then
		grep -q '^allowBuilds:' "$ws" || printf 'allowBuilds:\n' >> "$ws"
		awk -v k="  ${key}: true" '
			BEGIN { done=0 }
			/^allowBuilds:/ && !done { print; print k; done=1; next }
			{ print }
		' "$ws" > "$ws.tmp" && mv "$ws.tmp" "$ws"
		echo "    added allowBuilds: ${key}"
	fi
}

step_install_aidos() {
	# The aidos preset's tools run against a host-plane `aidos` core service
	# that the package's own dsh.bundle.patch mounts; `dsh plugin add`
	# installs it AND auto-mounts the patch (idempotent).
	if command -v dsh >/dev/null 2>&1; then
		dsh plugin --profile web add "$AIDOS_PLUGIN_SPEC"
	else
		echo "WARNING: dsh not on PATH; skipping aidos plugin install."
		echo "         Re-run './sync.sh' from a shell where dsh is installed."
	fi
}

step_sync_aidos_skills() {
	# Clone aidos at the PINNED commit from GitHub, then copy its skills/ out.
	# No local checkout is used — that would defeat the point of pinning.
	# If the pinned commit does not exist, panic and abort the whole sync.
	local spec="$AIDOS_PLUGIN_SPEC"
	local path ref owner repo url tmp
	path="${spec#github:}"
	ref="${spec##*#}"
	path="${path%#*}"
	owner="${path%%/*}"
	repo="${path##*/}"
	url="https://github.com/${owner}/${repo}.git"
	tmp="$(mktemp -d)"
	echo "=== cloning aidos skills ($url @ ${ref:0:12}) ==="
	if ! git clone "$url" "$tmp" 2>/dev/null; then
		echo "PANIC: could not clone $url"
		rm -rf "$tmp"
		exit 1
	fi
	if ! git -C "$tmp" checkout "$ref" 2>/dev/null; then
		echo "PANIC: pinned commit $ref does not exist in $url"
		rm -rf "$tmp"
		exit 1
	fi
	if [ ! -d "$tmp/skills" ]; then
		echo "WARNING: aidos has no skills/ directory at $ref; skipping skill sync"
		rm -rf "$tmp"
		return 0
	fi
	mkdir -p "$DSH_HOME/skills"
	cp -r "$tmp/skills/." "$DSH_HOME/skills/"
	echo "  synced aidos skills from pinned commit $ref"
	rm -rf "$tmp"
}

step_register_aidos_preset() {
	mkdir -p "$DSH_HOME/.agent-presets/aidos"
	# Source is the installed aidos package's preset. It carries the full
	# tool chain (tool-bash, tool-fs, etc). The old generator overwrote it
	# with a single-row loader, so bash-guard never ran.
	local src="$DSH_HOME/profiles/web/node_modules/aidos/presets/aidos/agent.cordis.yml"
	local fallback="$HERE/../aidos/presets/aidos/agent.cordis.yml"
	if [ ! -f "$src" ]; then
		if [ -f "$fallback" ]; then
			src="$fallback"
		else
			echo "  ERROR: aidos preset not found at $src"
			echo "         Run step_install_aidos first (dsh plugin add \$AIDOS_PLUGIN_SPEC), or clone aidos next to this repo."
			return 1
		fi
	fi
	# Copy the package's agent.cordis.yml verbatim, then rewrite the one
	# relative row that needs the deployed wrapper name.
	cp "$src" "$DSH_HOME/.agent-presets/aidos/agent.cordis.yml"
	# The package ships `- name: ./aidos-tools.js` (self-contained). The
	# deployed preset re-exports via an absolute shim, so rewrite that row.
	# Keep every other row (tool-bash, tool-fs, etc) verbatim.
	if rg -q '^[[:space:]]*-[[:space:]]*name:[[:space:]]*\./aidos-tools\.js' "$DSH_HOME/.agent-presets/aidos/agent.cordis.yml"; then
		sed -i 's#^[[:space:]]*-[[:space:]]*name:[[:space:]]*\./aidos-tools\.js#- name: ./aidos-loader.js#' "$DSH_HOME/.agent-presets/aidos/agent.cordis.yml"
	else
		if ! rg -q 'aidos-loader\.js' "$DSH_HOME/.agent-presets/aidos/agent.cordis.yml"; then
			echo "- name: ./aidos-loader.js" >> "$DSH_HOME/.agent-presets/aidos/agent.cordis.yml"
		fi
	fi
	cat > "$DSH_HOME/.agent-presets/aidos/aidos-loader.js" <<EOF
// Installed by sync.sh. Re-exports the aidos-tools plugin bundle from the
// aidos package installed via \`dsh plugin add\`.
//
// The import path is templated to an absolute path on purpose: preset
// compositions resolve bare specifiers against the installed harness, not
// the web profile, so a bare "aidos/..." specifier cannot load here.
export { name, inject, Config, apply } from "$DSH_HOME/profiles/web/node_modules/aidos/presets/aidos/aidos-tools.js";
EOF
	# Copy preset.yml from the same source; keep deployed order 3.
	local preset_src="$DSH_HOME/profiles/web/node_modules/aidos/presets/aidos/preset.yml"
	local preset_fallback="$HERE/../aidos/presets/aidos/preset.yml"
	if [ -f "$preset_src" ]; then
		cp "$preset_src" "$DSH_HOME/.agent-presets/aidos/preset.yml"
	elif [ -f "$preset_fallback" ]; then
		cp "$preset_fallback" "$DSH_HOME/.agent-presets/aidos/preset.yml"
	else
		cat > "$DSH_HOME/.agent-presets/aidos/preset.yml" <<'EOF'
name: Aidos
description: "The ticket board agent: plan, tickets, evidence, and state-gated tool access."
order: 3
EOF
		return 0
	fi
	if rg -q '^[[:space:]]*order:' "$DSH_HOME/.agent-presets/aidos/preset.yml"; then
		sed -i 's/^[[:space:]]*order:.*/order: 3/' "$DSH_HOME/.agent-presets/aidos/preset.yml"
	else
		echo "order: 3" >> "$DSH_HOME/.agent-presets/aidos/preset.yml"
	fi
}

step_patch_standard_preset_tool_subagent() {
	# Pin every subagent dispatched through the shipped `standard` preset
	# onto the `worker` profile chain (its first route). Done by editing the
	# shipped standard preset in place: the bundle owns the dsh install on
	# this machine, and re-running sync is idempotent. A dsh reinstall that
	# re-extracts the preset would silently revert; rerun sync to restore.
	#
	# Why: subagents inherit the parent agent's provider/model unless pinned,
	# so without this the main agent's orchestrator head (e.g. hy3-free)
	# leaks into subagent dispatches and the worker chain is never walked.
	#
	# Why not copy the preset: the user owns the install and prefers the
	# direct edit. The patch is one row in one file; no new preset directory.
	local dsh_bin dsh_pkg preset_yaml
	dsh_bin="$(command -v dsh 2>/dev/null || true)"
	if [ -z "$dsh_bin" ]; then
		echo "  WARNING: dsh not on PATH; skipping standard preset patch."
		return 0
	fi
	dsh_pkg="$(dirname "$(dirname "$(realpath "$dsh_bin")")")"
	preset_yaml="$dsh_pkg/config/agent-presets/standard/agent.cordis.yml"
	if [ ! -f "$preset_yaml" ]; then
		echo "  WARNING: standard preset not found at $preset_yaml; skipping."
		return 0
	fi

	local worker_head
	worker_head="$(WORKER_YAML="$HERE/home/settings.yaml" python3 - <<'PY'
import os, sys, yaml
d = yaml.safe_load(open(os.environ['WORKER_YAML'])) or {}
routes = ((d.get('profile') or {}).get('chains') or {}).get('worker', {}).get('routes') or []
if not routes:
    sys.exit('no worker chain routes in home/settings.yaml')
r = routes[0]
print(f"{r['provider']} {r['model']}")
PY
	)" || { echo "  ERROR: failed to read worker head: $worker_head"; return 1; }
	local w_provider="${worker_head%% *}"
	local w_model="${worker_head#* }"

	python3 - "$preset_yaml" "$w_provider" "$w_model" <<'PY'
import re, sys
# Comment-preserving patch of the shipped standard preset. PyYAML round-trip
# drops comments and rewrites indentation, making the resulting diff huge.
# The dsh-tool-subagent rows have a deterministic shape, so a targeted line
# scan that only touches the config block is both safe and minimal.
#
# Each row of interest (indent shown for tool-subagent nested in delegation):
#     - id: tool-subagent[-fork]
#       name: '@deepseek-ai/dsh-tool-subagent'
#       [disabled: true]            <- skipped
#       config:
#         provider: ...
#         toolName: subagent[_fork]
#         backgroundMode: continuable
#
# We insert (or replace) `agentOptions:` with the worker head immediately
# after `backgroundMode: continuable`, matching the existing 6/8-space
# indent used by the surrounding keys.
path, provider, model = sys.argv[1], sys.argv[2], sys.argv[3]
indent6 = '      '   # config keys
indent8 = '        '  # agentOptions values
new_block = (
    f"{indent6}agentOptions:\n"
    f"{indent8}provider: {provider}\n"
    f"{indent8}model: {model}\n"
)
with open(path) as f:
    lines = f.read().splitlines(keepends=True)
def row_indent(s):
    return len(s) - len(s.lstrip(' '))
edits = 0; skipped = 0
out = []
i = 0
while i < len(lines):
    line = lines[i]
    # Anchor: a `- id:` line whose next non-blank line is
    # `name: '@deepseek-ai/dsh-tool-subagent'`.
    if (line.lstrip().startswith('- id:')
        and i + 1 < len(lines)
        and "name: '@deepseek-ai/dsh-tool-subagent'" in lines[i + 1]):
        start = i
        row_indent_val = row_indent(lines[start])
        # Walk forward to find the row's end: blank line, shallower indent,
        # or another `- ...` at the same indent.
        j = start + 1
        while j < len(lines):
            ln = lines[j]
            if not ln.strip(): break
            ind = row_indent(ln)
            if ind < row_indent_val: break
            if ind == row_indent_val and ln.lstrip().startswith('- '): break
            j += 1
        row_lines = lines[start:j]
        row_text = ''.join(row_lines)
        # Skip disabled rows (tool-subagent-codex, tool-subagent-claude-code).
        if re.search(r'^\s+disabled:\s*true\s*$', row_text, re.MULTILINE):
            skipped += 1; out.extend(row_lines); i = j; continue
        # Already pinned with these values? Leave as-is.
        if re.search(rf'^{re.escape(indent6)}agentOptions:\s*$', row_text, re.MULTILINE):
            new_row_text = re.sub(
                rf'^{re.escape(indent6)}agentOptions:\n(?:{re.escape(indent8)}(?:provider|model):[^\n]*\n)+',
                new_block, row_text, count=1, flags=re.MULTILINE,
            )
            if new_row_text != row_text:
                edits += 1; out.append(new_row_text)
            else:
                skipped += 1; out.append(row_text)
            i = j; continue
        # Not pinned: insert new_block after the row's `backgroundMode:` line.
        new_row_lines = []
        inserted = False
        for rl in row_lines:
            new_row_lines.append(rl)
            if not inserted and re.match(r'^\s+backgroundMode:[^\n]*\n$', rl):
                new_row_lines.append(new_block)
                inserted = True
        if inserted:
            edits += 1; out.extend(new_row_lines)
        else:
            skipped += 1; out.extend(row_lines)
        i = j; continue
    out.append(line)
    i += 1
if edits == 0:
    print(f'  {skipped} tool-subagent row(s) unchanged (already pinned or disabled); no change')
    sys.exit(0)
with open(path, 'w') as f:
    f.writelines(out)
print(f'  pinned {edits} tool-subagent row(s) to {provider}/{model}; {skipped} unchanged')
PY
}

step_set_defaults() {
	# Regenerate $DSH_HOME/settings.yaml from the known-good repo template
	# ($HERE/home/settings.yaml). The local file is stateless: it holds no
	# secrets, so sync may overwrite it freely. profile.active is the one
	# runtime decision (the profiles tool flips it), so preserve the current
	# value; every other section comes from the template.
	local active
	active="$(python3 - "$DSH_HOME/settings.yaml" <<'PY'
import sys, yaml
try:
    d = yaml.safe_load(open(sys.argv[1])) or {}
except Exception:
    d = {}
print(d.get('profile', {}).get('active', 'personal'))
PY
)"
	cp "$HERE/home/settings.yaml" "$DSH_HOME/settings.yaml"
	# Strip build-time modelSync timestamp: it is local state, not template (M18)
	if rg -q "^modelSync:" "$DSH_HOME/settings.yaml"; then
		python3 - "$DSH_HOME/settings.yaml" <<'M18PY'
import pathlib, re, os
p = pathlib.Path(os.environ.get("DSH_HOME", os.path.expanduser("~/.dsh")) + "/settings.yaml")
text = p.read_text()
text = re.sub(r"\nmodelSync:\n(?:  .*\n?)*", "\n", text)
p.write_text(text)
M18PY
	fi
	# Byte-preserving patch of the single runtime line. A full YAML round-trip
	# would let PyYAML (YAML 1.1) rewrite the file, mangling e.g. the
	# reasoningEfforts key `off:` into `false: null` (YAML 1.1 treats `off` as
	# boolean), which the llm-pi-ai schema rejects and which would drop every
	# pi-ai provider. Only touch the `profile.active` value.
	if [ "$active" != "personal" ]; then
		if ! sed -i "s/^  active: .*$/  active: $active/" "$DSH_HOME/settings.yaml"; then echo "ERROR: failed to patch active" >&2; exit 1; fi
		if ! rg -q "^  active: $active$" "$DSH_HOME/settings.yaml"; then echo "ERROR: active patch had no effect (expected $active)" >&2; exit 1; fi
	fi
}

step_ignore_better_edit_dir() {
	# The hashline editor drops a .dsh_better_edit/ state directory into
	# whatever repo a session edits files in. It is a tool artifact that
	# belongs in no repository, so ignore it once per machine rather than per
	# repo. Honor an existing core.excludesFile; otherwise use git's XDG
	# default path, which git reads with no extra configuration when
	# core.excludesFile is unset.
	git_ignore=""
	if command -v git >/dev/null 2>&1; then
		git_ignore="$(git config --get core.excludesFile || true)"
	fi
	if [ -n "$git_ignore" ]; then
		git_ignore="${git_ignore/#\~/$HOME}"
	else
		git_ignore="${XDG_CONFIG_HOME:-$HOME/.config}/git/ignore"
	fi
	mkdir -p "$(dirname "$git_ignore")"
	touch "$git_ignore"
	if grep -qxF '.dsh_better_edit/' "$git_ignore"; then
		echo "    already ignored in $git_ignore"
	else
		cat >> "$git_ignore" <<'EOF'

# dsh-better-edit (hashline) scratch/state directory. A tool artifact that
# appears in whatever repo a session edits files in. Never belongs in a repo.
.dsh_better_edit/
EOF
		echo "    added .dsh_better_edit/ to $git_ignore"
	fi
}

# ── step table ────────────────────────────────────────────────────────────────
# Each entry: "Human title|function_name". Numbers derive from the array, so
# adding, removing, or reordering steps needs NO manual renumbering.
STEPS=(
	"Install repo dev deps (esbuild for the build step)|step_install_deps"
	"Build the personal plugins|step_build_plugins"
	"Sync skills -> $DSH_HOME/skills|step_sync_skills"
	"Sync AGENTS.md -> $DSH_HOME/AGENTS.md|step_sync_agents_md"
	"Sync dsh-better-edit guidance overrides|step_sync_better_edit_guidance"
	"Sync bash-guard rule drop-ins -> $DSH_HOME/plugins/guards|step_sync_guard_rules"
	"Write the web-profile patch (host-plane rows)|step_write_web_patch"
	"Install the third-party plugin set on the web profile|step_install_plugins"
	"Report extra plugins (removal commands)|step_report_extra_plugins"
	"Allow aidos build scripts in web pnpm-workspace.yaml|step_allow_aidos_build"
	"Install the aidos plugin from git|step_install_aidos"
	"Sync aidos skills from pinned commit|step_sync_aidos_skills"
	"Pin subagents onto the worker chain (patch standard preset)|step_patch_standard_preset_tool_subagent"
	"Register the aidos agent preset|step_register_aidos_preset"
	"Regenerate settings.yaml from the repo template|step_set_defaults"
	"Ensure .dsh_better_edit/ is ignored by git machine-wide|step_ignore_better_edit_dir"
)

main() {
	local n=0
	local total=${#STEPS[@]}
	for entry in "${STEPS[@]}"; do
		n=$((n + 1))
		echo "=== [$n/$total] ${entry%%|*}"
		"${entry##*|}"
	done
}

main

echo
echo "Done. Restart dsh web to pick up the new bundle layer (bundle rows are"
echo "static per boot; skills/presets are discovered live on the next session)."
echo
echo "Installed:"
echo "  skills:  $DSH_HOME/skills"
echo "  rules:   $DSH_HOME/AGENTS.md"
echo "  guards:  $DSH_HOME/plugins/guards"
echo "  patch:   $DSH_HOME/profiles/web/cordis.patch.yml"
echo "  preset:  $DSH_HOME/.agent-presets/aidos"
