#!/usr/bin/env bash
# dsh personal bundle installer — idempotent.
#
# Usage:  clone the dotfiles-ai repo, cd into it, run ./sync.sh
#   ./sync.sh                          # installs into $DSH_HOME (default ~/.dsh)
#   DSH_HOME=/path/to/home ./sync.sh
#   AIDOS_PLUGIN_SPEC=github:you/aidos ./sync.sh   # override the aidos git spec
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$HERE"
export DSH_HOME="${DSH_HOME:-$HOME/.dsh}"
AIDOS_PLUGIN_SPEC="${AIDOS_PLUGIN_SPEC:-github:xyzshantaram/aidos#4b1e14e1440cdb11257d9ac4f66d0f09d382d195}"


step_install_deps() {
	(cd "$REPO" && pnpm install)
}

step_build_plugins() {
	(cd "$HERE" && node build.mjs)
}

step_sync_skills() {
	mkdir -p "$DSH_HOME/skills"
	cp -r "$HERE/skills/." "$DSH_HOME/skills/"
}

step_sync_agents_md() {
	cp "$HERE/home/AGENTS.md" "$DSH_HOME/AGENTS.md"
}

step_sync_better_edit_guidance() {
	mkdir -p "$DSH_HOME/plugins/dsh-better-edit"
	cp -r "$HERE/home/plugins/dsh-better-edit/." "$DSH_HOME/plugins/dsh-better-edit/"
}

step_sync_guard_rules() {
	mkdir -p "$DSH_HOME/plugins/guards"
	cp -r "$HERE/guards/." "$DSH_HOME/plugins/guards/"
}

step_write_web_patch() {
	patch_dir="$DSH_HOME/profiles/web"
	mkdir -p "$patch_dir"
	cat > "$patch_dir/cordis.patch.yml" <<PATCH
# Auto-generated by $HERE/sync.sh. Do not hand-edit; re-run the script instead.
# Personal bundle host-plane rows: these apply to EVERY session regardless of
# preset — the MCP servers, the bash guard (rules read live from
# $DSH_HOME/plugins/guards/*.json), the manifest guard, the package tool,
# and the profile-routed see vision helper. The plugin files resolve their
# @deepseek-ai/* imports against the host base (dsh install node_modules);
# unbash + the walker are bundled inside each plugin file.
- insert:
    - id: mcp-nostrbook
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: nostrbook
        transport: stdio
        command: npx
        args: ['-y', '@nostrbook/mcp@latest']
    - id: mcp-gitlab
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: gitlab
        transport: stdio
        command: glab
        args: ['mcp', 'serve']
    - id: mcp-swiggy-food
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: swiggy-food
        transport: streamable-http
        url: https://mcp.swiggy.com/food
    - id: mcp-swiggy-instamart
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: swiggy-instamart
        transport: streamable-http
        url: https://mcp.swiggy.com/im
    - id: mcp-git
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: git
        transport: stdio
        command: uvx
        args: ['mcp-server-git']
    - id: bash-guard
      name: $HERE/plugins/bash-guard.js
      config:
        guardsDir: $DSH_HOME/plugins/guards
    - id: manifest-guard
      name: $HERE/plugins/manifest-guard.js
    - id: package-tool
      name: $HERE/plugins/package-tool.js
    - id: skill-gate
      name: $HERE/plugins/skill-gate.js
    - id: see
      name: $HERE/plugins/see.js
    - id: tmp-dsh-shared
      name: $HERE/plugins/tmp-dsh-shared.js
    - id: grant
      name: $HERE/plugins/grant.js

    - id: ask-interrupt
      name: $HERE/plugins/ask-interrupt.js


    - id: profiles
      name: $HERE/plugins/profiles.js
    # The cordis_* tools, gated behind the two cordis skills via skill-gate.
    - id: tool-cordis
      name: '@deepseek-ai/dsh-tool-cordis'
    - id: compaction-instant
      name: '@deepseek-ai/dsh-compaction-basic'
    - id: tool-recall
      name: '@deepseek-ai/dsh-compaction-basic/tool'
    - id: command-recall
      name: '@deepseek-ai/dsh-compaction-basic/command'


# Config override for the self-mounting dsh-remote plugin (the plugin
# install step pins our fork). The plugin creates the remote row from its
# own bundle patch, so this MUST be a top-level override row, NOT a child
# of the insert list above: an insert row with the same id kills boot with
# "duplicate loader entry id: remote".
#
# applyEntryPatches assigns each override key WHOLESALE (target[key] = value,
# dsh-app-boot/lib/index.js). It does not deep-merge, so the block below must
# repeat every default from the plugin's own cordis.patch.yml. Only two values
# differ from those defaults:
#   session.secure: the proxy terminates TLS, so the cookie may carry Secure.
#   debug: registers POST /auth/trace, which writes client trace lines to the
#     server journal. Keep it false unless you debug a remote-mode fault. The
#     client half only ships traces when the page URL also carries ?dshTrace=1.
- id: remote
  config:
    enabled: true
    debug: true
    accounts: []
    secret: ''
    session:
      cookieName: dsh_session
      ttlSeconds: 604800
      secure: true
      sameSite: lax
    enforceRoles: true
    rateLimit:
      maxAttempts: 5
      windowMs: 900000
    files:
      roots:
        - /tmp/dsh

PATCH
}

step_install_plugins() {
	# Idempotent: a repeat `dsh plugin add` of an installed spec converges
	# instead of duplicating a row.
	if command -v dsh >/dev/null 2>&1; then
		# One install helper: print the plugin name, keep pnpm quiet, and
		# surface only warnings and errors (or the full output on failure).
		pnpm_ins() {
			local spec="$1" name
			name="$(printf '%s' "$spec" | sed -E 's#.*github.com/[^/]+/([^/#]+)/archive.*#\1#; s/#[^/]*$//; s#.*[/:]##')"
			name="${name%%@*}"
			echo "  installing ${name:-$spec}"
			local out rc
			out="$(dsh plugin --profile web add "$spec" 2>&1)"
			rc=$?
			if [ "$rc" -ne 0 ]; then printf '%s\n' "$out"; return "$rc"; fi
			printf '%s\n' "$out" | rg -i 'warn|error' || true
		}
		pnpm_ins "github:sunshaobei/dsh-input-history#9b5b7a494a5c"
		pnpm_ins "github:omdsh-dev/dsh-tool-calculator#05090e946113"
		pnpm_ins "github:omdsh-dev/dsh-tool-diff#d4afd6e2de0b"
		# The four tools the `util` skill gates (ticket E4). Installed as
		# separate repos, NOT through the omdsh-dev/dsh-toolkit monorepo:
		# that collection also registers calculator and diff, which are
		# already installed above and would be double-registered.
		pnpm_ins "github:omdsh-dev/dsh-tool-time#8b7a2137f516"
		pnpm_ins "github:omdsh-dev/dsh-tool-regex#5afda86cd686"
		pnpm_ins "github:omdsh-dev/dsh-tool-markdown#267871b115c4"
		pnpm_ins "github:omdsh-dev/dsh-tool-encoding#dbf829b5a755"
		pnpm_ins "https://github.com/omdsh-dev/dsh-at-file/archive/refs/tags/v0.6.7.tar.gz"
		# dsh plugin --profile web add dsh-worktree
		pnpm_ins "github:Tieboyh/dsh-session-search#82990a0e9804"
		# Remote-access auth: dsh serves settings RPCs loopback-only, so every
		# proxied browser gets inert settings scopes without this plugin.
		# Self-mounts via its own bundle patch; the patch step adds the
		# config row (secure cookie, debug trace). Pinned to OUR fork
		# (github.com/xyzshantaram/dsh-remote); upgrade = bump the pin.
		pnpm_ins "github:xyzshantaram/dsh-remote#0c9e708c2b5c"
		# Streaming markdown renderer (Mermaid, KaTeX, Shiki); client-only.
		pnpm_ins "dsh-better-markdown@0.1.2"
		# Paste-to-path: pasted files land under <workspace>/.dsh/pastes/ and
		# the composer carries a PATH reference. Replaced dsh-paste-input.
		pnpm_ins "github:Johnny-xuan/dsh-paste-to-path#d68fb104ca25a663ba3912bb17f8c2ab32d60e37"

		pnpm_ins "$HERE/plugins/session-archive"
		pnpm_ins "$HERE/plugins/subscriptions"
		pnpm_ins "$HERE/plugins/tool-render"
		pnpm_ins "$HERE/plugins/profiles-client"
		pnpm_ins "$HERE/plugins/approval-comment"
	else
		echo "WARNING: dsh not on PATH; skipping third-party plugin installs."
		echo "         Re-run './sync.sh' from a shell where dsh is installed."
	fi
}

step_report_extra_plugins() {
	# Print removal commands for plugins installed on the web profile that are
	# NOT part of this bundle's set. sync.sh only ever ADDS plugins, so a
	# plugin dropped from the set above stays installed until removed; this
	# step surfaces the exact command. It prints only, never removes.
	if ! command -v dsh >/dev/null 2>&1; then
		echo "WARNING: dsh not on PATH; skipping extra-plugin check."
		return 0
	fi
	# Exact package names this bundle installs (the pnpm_ins specs above plus
	# aidos), and the profile's own base deps that are not extras. Keep this
	# in sync with the pnpm_ins list when you add or drop a plugin.
	local expected=(
		"@deepseek-ai/dsh-tool-calculator"
		"@deepseek-ai/dsh-tool-diff"
		"@deepseek-ai/dsh-tool-encoding"
		"@deepseek-ai/dsh-tool-markdown"
		"@deepseek-ai/dsh-tool-regex"
		"@deepseek-ai/dsh-tool-time"
        "@deepseek-ai/dsh-compaction-basic"
		"@dsh-external/dsh-session-search"
		"@xgone/dsh-remote"
		"aidos"
		"approval-comment"
		"dsh-at-file"
		"dsh-better-markdown"
		"dsh-input-history"
		"dsh-paste-to-path"
		"profiles-client"
		"session-archive"
		"subscriptions"
		"tool-render"
	)
	local base=(
		"@deepseek-ai/dsh-client-ui-attachment"
		"@deepseek-ai/dsh-client-web-react"
		"dsh-better-edit"
	)
	local installed extra=0 name
	installed="$(dsh plugin --profile web list --depth 0 --json 2>/dev/null | python3 -c '
import json, sys
try:
    data = json.load(sys.stdin)
except Exception:
    sys.exit(0)
proj = data[0] if isinstance(data, list) and data else data
if not isinstance(proj, dict):
    sys.exit(0)
for key in (proj.get("dependencies") or {}):
    print(key)
')"
	if [ -z "$installed" ]; then
		echo "  (could not read the installed plugin list; skipping extra check)"
		return 0
	fi
	for name in $installed; do
		case " ${expected[*]} ${base[*]} " in
			*" $name "*) ;;
			*)
				echo "  extra plugin: $name"
				echo "    dsh plugin --profile web remove $name"
				extra=1
				;;
		esac
	done
	[ "$extra" -eq 0 ] && echo "  no extra plugins."
}

step_allow_aidos_build() {
	# pnpm refuses to run a package's install/build scripts unless its exact
	# resolved tarball URL is listed under `allowBuilds` in the web profile's
	# pnpm-workspace.yaml. aidos needs its postinstall, so add the entry for the
	# CURRENT pin (AIDOS_PLUGIN_SPEC) idempotently. The pin changes per bump, so
	# we reconstruct the codeload tarball URL the same way pnpm does from the
	# github spec (owner/repo#ref -> tarball, name = repo basename).
	local ws="$DSH_HOME/profiles/web/pnpm-workspace.yaml"
	local spec="${AIDOS_PLUGIN_SPEC}"
	local path ref name tarball key
	path="${spec#github:}"
	ref="${spec##*#}"
	path="${path%#*}"
	name="$(basename "$path")"
	tarball="https://codeload.github.com/${path}/tar.gz/${ref}"
	key="${name}@${tarball}"
	mkdir -p "$(dirname "$ws")"
	touch "$ws"
	if ! grep -qxF "  ${key}: true" "$ws"; then
		grep -q '^allowBuilds:' "$ws" || printf 'allowBuilds:\n' >> "$ws"
		awk -v k="  ${key}: true" '
			BEGIN { done=0 }
			/^allowBuilds:/ && !done { print; print k; done=1; next }
			{ print }
		' "$ws" > "$ws.tmp" && mv "$ws.tmp" "$ws"
		echo "    added allowBuilds: ${key}"
	fi
}

step_install_aidos() {
	# The aidos preset's tools run against a host-plane `aidos` core service
	# that the package's own dsh.bundle.patch mounts; `dsh plugin add`
	# installs it AND auto-mounts the patch (idempotent).
	if command -v dsh >/dev/null 2>&1; then
		dsh plugin --profile web add "$AIDOS_PLUGIN_SPEC"
	else
		echo "WARNING: dsh not on PATH; skipping aidos plugin install."
		echo "         Re-run './sync.sh' from a shell where dsh is installed."
	fi
}

step_register_aidos_preset() {
	mkdir -p "$DSH_HOME/.agent-presets/aidos"
	cat > "$DSH_HOME/.agent-presets/aidos/agent.cordis.yml" <<'EOF'
# The aidos agent preset composition (installed by sync.sh).
# The loader re-exports the aidos-tools bundle from the installed aidos
# package by absolute path. Preset rows resolve bare specifiers against
# the installed harness, which has no aidos package; only an absolute
# path reaches the web profile's node_modules.
- name: ./aidos-loader.js
EOF
	cat > "$DSH_HOME/.agent-presets/aidos/aidos-loader.js" <<EOF
// Installed by sync.sh. Re-exports the aidos-tools plugin bundle from the
// aidos package installed via `dsh plugin add`.
//
// The import path is templated to an absolute path on purpose: preset
// compositions resolve bare specifiers against the installed harness, not
// the web profile, so a bare "aidos/..." specifier cannot load here.
export { name, inject, Config, apply } from "$DSH_HOME/profiles/web/node_modules/aidos/presets/aidos/aidos-tools.js";
EOF
	cat > "$DSH_HOME/.agent-presets/aidos/preset.yml" <<'EOF'
name: Aidos
description: "The ticket board agent: plan, tickets, evidence, and state-gated tool access."
order: 3
EOF
}

step_set_defaults() {
	# Regenerate $DSH_HOME/settings.yaml from the known-good repo template
	# ($HERE/home/settings.yaml). The local file is stateless: it holds no
	# secrets, so sync may overwrite it freely. profile.active is the one
	# runtime decision (the profiles tool flips it), so preserve the current
	# value; every other section comes from the template.
	local active
	active="$(python3 - "$DSH_HOME/settings.yaml" <<'PY'
import sys, yaml
try:
    d = yaml.safe_load(open(sys.argv[1])) or {}
except Exception:
    d = {}
print(d.get('profile', {}).get('active', 'personal'))
PY
)"
	cp "$HERE/home/settings.yaml" "$DSH_HOME/settings.yaml"
	python3 - "$DSH_HOME/settings.yaml" "$active" <<'PY'
import sys, yaml
p, active = sys.argv[1], sys.argv[2]
d = yaml.safe_load(open(p))
d['profile']['active'] = active
with open(p, 'w') as f:
    yaml.safe_dump(d, f, sort_keys=False)
PY
}

step_ignore_better_edit_dir() {
	# The hashline editor drops a .dsh_better_edit/ state directory into
	# whatever repo a session edits files in. It is a tool artifact that
	# belongs in no repository, so ignore it once per machine rather than per
	# repo. Honor an existing core.excludesFile; otherwise use git's XDG
	# default path, which git reads with no extra configuration when
	# core.excludesFile is unset.
	git_ignore=""
	if command -v git >/dev/null 2>&1; then
		git_ignore="$(git config --get core.excludesFile || true)"
	fi
	if [ -n "$git_ignore" ]; then
		git_ignore="${git_ignore/#\~/$HOME}"
	else
		git_ignore="${XDG_CONFIG_HOME:-$HOME/.config}/git/ignore"
	fi
	mkdir -p "$(dirname "$git_ignore")"
	touch "$git_ignore"
	if grep -qxF '.dsh_better_edit/' "$git_ignore"; then
		echo "    already ignored in $git_ignore"
	else
		cat >> "$git_ignore" <<'EOF'

# dsh-better-edit (hashline) scratch/state directory. A tool artifact that
# appears in whatever repo a session edits files in. Never belongs in a repo.
.dsh_better_edit/
EOF
		echo "    added .dsh_better_edit/ to $git_ignore"
	fi
}

# ── step table ────────────────────────────────────────────────────────────────
# Each entry: "Human title|function_name". Numbers derive from the array, so
# adding, removing, or reordering steps needs NO manual renumbering.
STEPS=(
	"Install repo dev deps (esbuild for the build step)|step_install_deps"
	"Build the personal plugins|step_build_plugins"
	"Sync skills -> $DSH_HOME/skills|step_sync_skills"
	"Sync AGENTS.md -> $DSH_HOME/AGENTS.md|step_sync_agents_md"
	"Sync dsh-better-edit guidance overrides|step_sync_better_edit_guidance"
	"Sync bash-guard rule drop-ins -> $DSH_HOME/plugins/guards|step_sync_guard_rules"
	"Write the web-profile patch (host-plane rows)|step_write_web_patch"
	"Install the third-party plugin set on the web profile|step_install_plugins"
	"Report extra plugins (removal commands)|step_report_extra_plugins"
	"Allow aidos build scripts in web pnpm-workspace.yaml|step_allow_aidos_build"
	"Install the aidos plugin from git|step_install_aidos"
	"Register the aidos agent preset|step_register_aidos_preset"
	"Regenerate settings.yaml from the repo template|step_set_defaults"
	"Ensure .dsh_better_edit/ is ignored by git machine-wide|step_ignore_better_edit_dir"
)

main() {
	local n=0
	local total=${#STEPS[@]}
	for entry in "${STEPS[@]}"; do
		n=$((n + 1))
		echo "=== [$n/$total] ${entry%%|*}"
		"${entry##*|}"
	done
}

main

echo
echo "Done. Restart dsh web to pick up the new bundle layer (bundle rows are"
echo "static per boot; skills/presets are discovered live on the next session)."
echo
echo "Installed:"
echo "  skills:  $DSH_HOME/skills"
echo "  rules:   $DSH_HOME/AGENTS.md"
echo "  guards:  $DSH_HOME/plugins/guards"
echo "  patch:   $DSH_HOME/profiles/web/cordis.patch.yml"
echo "  preset:  $DSH_HOME/.agent-presets/aidos"
