#!/usr/bin/env -S deno run --no-lock --allow-read --allow-write --allow-run --allow-env --allow-sys --allow-net
//
// A wizard walks a human through a manual procedure, step by step.
// Generated by the /wizard skill.
//
// Everything above the "STAGES" marker is the wizard library: do not hand-edit
// it. Author each stage below the marker as one named Pipeline step.
//
// Copy this file to the target path, replace the example steps, and run:
//   deno check <wizard>.ts
//   deno run --no-lock --allow-read --allow-write --allow-run --allow-env <wizard>.ts
//
// Self contained: pinned npm: imports resolve from the Deno cache.
// --no-lock keeps Deno from writing a deno.lock file. Nothing touches
// package.json, pnpm-lock.yaml, or node_modules.

import {
  ask,
  ask_secret,
  banner,
  createWizard,
  finish,
  open_url,
  say,
  set_secret,
  setTotalStages,
  step,
  write_env,
} from "../src/wizardkit.ts";

// STAGES: AGENT EDIT BELOW. One Pipeline step per stage. Set TOTAL_STAGES to match.
// zx escape hatch: use $`cmd args` for shell, e.g. await $`gh auth status`.
setTotalStages(2);

await banner("Stripe setup");
// AGENT EDIT BELOW: replace example steps with real steps.
await createWizard<{ "publishable-key": string; "secret-key": string }>()
  .step(
    "publishable-key",
    async () => {
      say("Grab test keys for local dev + CI.");
      await open_url("https://dashboard.stripe.com/test/apikeys");
      step("Copy the Publishable key (starts pk_test_).");
      const v = await ask("STRIPE_PUBLISHABLE_KEY", "Paste the publishable key:");
      await write_env("STRIPE_PUBLISHABLE_KEY", v);
      return v;
    },
    { validate: (v) => (String(v).trim() ? true : "Paste the publishable key.") },
  )
  .step(
    "secret-key",
    async () => {
      step("Click 'Reveal test key', then copy it.");
      const v = await ask_secret("STRIPE_SECRET_KEY", "Paste the secret key:");
      await write_env("STRIPE_SECRET_KEY", v);
      await set_secret("STRIPE_SECRET_KEY", v);
      return v;
    },
    { validate: (v) => (String(v).trim() ? true : "Paste the secret key.") },
  )
  .run();
await finish();
