#!/usr/bin/env -S deno run --no-lock --allow-read --allow-write --allow-run --allow-env --allow-sys --allow-net
//
// A wizard walks a human through a manual procedure, step by step.
// Generated by the /wizard skill.
//
// Everything above the "STAGES" marker is the wizard library: do not hand-edit
// it. Author each stage below the marker as one named Pipeline step.
//
// Copy this file to the target path, replace the example steps, and run:
//   deno check <wizard>.ts
//   deno run --no-lock --allow-read --allow-write --allow-run --allow-env <wizard>.ts
//
// Self contained: pinned npm: imports resolve from the Deno cache.
// --no-lock keeps Deno from writing a deno.lock file. Nothing touches
// package.json, pnpm-lock.yaml, or node_modules.

import { $ } from "zx";
import { MepCLI } from "mepcli";
import {
  APP_VERSION,
  banner,
  clearScreen,
  createWizard,
  finish,
  menuSeparator,
  say,
  selectHint,
  setTotalStages,
  step,
  warn,
  wizardExit,
  wrap,
} from "../src/wizardkit.ts";

// STAGES: AGENT EDIT BELOW. One Pipeline step per stage. Set TOTAL_STAGES to match.
// zx escape hatch: use $`cmd args` for shell, e.g. await $`gh auth status`.
setTotalStages(1);

import { listRuns, type RunMeta, stateRoot } from "../src/runstate.ts";
import { createRunLog, type RunLog } from "../src/log.ts";
import { fetchShareLink } from "../src/share.ts";
import { loadSettings, pickCurrency, saveSettings } from "../src/settings.ts";
import { setupSplitwise } from "../src/splitwise-setup.ts";
import { printAiSetup } from "../src/ai-setup.ts";

// Repo root holds the wizards dir and the scripts dir.
const ROOT = decodeURIComponent(new URL("..", import.meta.url).pathname).replace(/\/+$/, "");

// True when the user passed --dry on the command line.
const DRY = Deno.args.includes("--dry");

// Print the dry plan with exact commands and exit without side effects.
// deno-lint-ignore require-await -- main awaits this in dry mode, so it keeps async.
async function printDryPlan(): Promise<void> {
  say("Main menu dry run. Nothing runs and nothing is written.");
  step(
    "1 Start here: save usage, then run wizards/settings.ts, then offer Splitwise setup or the AI setup prompt",
  );
  step(
    "2 Split and push recent orders: run wizards/gatherer.ts, then wizards/splitter.ts <runId>, then wizards/pusher.ts <runId>",
  );
  step(
    "3 Pick up where you left off: list runs with listRuns, then run the next wizard for the picked run",
  );
  step("4 Collect orders from platforms: run wizards/gatherer.ts");
  step("5 Assign per-order split: read runs with listRuns, then run wizards/splitter.ts <runId>");
  step(
    "6 Upload orders to Splitwise: run wizards/pusher.ts <runId>, or fetch a share link with fetchShareLink and then run wizards/pusher.ts <file>",
  );
  step("7 Settings: run wizards/settings.ts");
  step("8 Set up with an AI assistant: print a copyable prompt block");
  step("9 Exit");
}

// True when the named wizard file exists in the wizards dir.
async function wizardExists(name: string): Promise<boolean> {
  try {
    // Stat the file and accept plain files only.
    const info = await Deno.stat(ROOT + "/wizards/" + name);
    return info.isFile;
  } catch {
    return false;
  }
}

// Run one child wizard with inherited stdio and return its exit code.
async function runWizard(file: string, extra: string[]): Promise<number> {
  // Record the exact command in the run log only.
  log.write("info", "run wizards/" + file + (extra.length > 0 ? " " + extra.join(" ") : ""));
  try {
    // Keep child output on the same terminal.
    // Mark the child as menu owned so it can return cleanly.
    const env = { ...Deno.env.toObject(), SPLIT_UTILS_FROM_MENU: "1" };
    await $({ cwd: ROOT, stdio: "inherit", env })`deno run -A --no-lock ${
      "wizards/" + file
    } ${extra}`;
    return 0;
  } catch (e) {
    // Read the exit code from the failed process.
    const code = (e as { exitCode?: unknown }).exitCode;
    return typeof code === "number" ? code : 1;
  }
}

// Print the id and reason of every failed run.
async function reportFailedRuns(): Promise<void> {
  // Load all live runs from the state root.
  const runs = await listRuns();
  // Keep runs with failed status only.
  const failed = runs.filter((r) => r.status === "failed");
  if (failed.length === 0) {
    // Stay silent when nothing failed. The menu speaks for itself.
    return;
  }
  for (const run of failed) {
    say("Failed run " + run.id + ": " + (run.failureReason ?? "no reason recorded"));
  }
}

// Ask the user to pick one run with the given status.
async function pickRun(status: "gathered" | "assigned"): Promise<string | null> {
  // Load runs and keep the wanted status only.
  const runs = (await listRuns()).filter((r) => r.status === status);
  if (runs.length === 0) {
    say("No runs with status " + status + " found.");
    return null;
  }
  return await MepCLI.select({
    message: "Pick a run" + selectHint(),
    choices: runs.map((r) => ({ title: r.id + " " + r.label, value: r.id })),
  });
}

// Run gatherer, then splitter, then pusher, each only on success.
async function runWholeFlow(): Promise<void> {
  if (!(await wizardExists("gatherer.ts"))) {
    say("Collecting orders is not available yet.");
    return;
  }
  if (!(await wizardExists("splitter-cliffy.ts"))) {
    say("Assigning splits is not available yet.");
    return;
  }
  if (!(await wizardExists("pusher.ts"))) {
    say("Uploading orders is not available yet.");
    return;
  }
  // Stop when gather fails and show failed runs.
  const gatherCode = await runWizard("gatherer.ts", []);
  if (gatherCode !== 0) {
    if (gatherCode === 130) say("Cancelled.");
    else await reportFailedRuns();
    return;
  }
  // ListRuns sorts newest first, so the head is the fresh run.
  const gathered = (await listRuns()).filter((r) => r.status === "gathered");
  if (gathered.length === 0) {
    say("Gather finished but no gathered run found.");
    return;
  }
  const runId = gathered[0].id;
  // Stop when split fails and show failed runs.
  const splitCode = await runWizard("splitter-cliffy.ts", [runId]);
  if (splitCode !== 0) {
    if (splitCode === 130) say("Cancelled.");
    else await reportFailedRuns();
    return;
  }
  // Push the same run and show failed runs on failure.
  const pushCode = await runWizard("pusher.ts", [runId]);
  if (pushCode !== 0) {
    if (pushCode === 130) say("Cancelled.");
    else await reportFailedRuns();
  }
}

// Dispatch the gatherer wizard on its own.
async function gatherOrders(): Promise<void> {
  if (!(await wizardExists("gatherer.ts"))) {
    say("Collecting orders is not available yet.");
    return;
  }
  const code = await runWizard("gatherer.ts", []);
  if (code !== 0) {
    if (code === 130) say("Cancelled.");
    else await reportFailedRuns();
  }
}

// Dispatch the splitter wizard on a picked gathered run.
async function assignSplits(): Promise<void> {
  if (!(await wizardExists("splitter-cliffy.ts"))) {
    say("Assigning splits is not available yet.");
    return;
  }
  const runId = await pickRun("gathered");
  if (runId === null) return;
  const code = await runWizard("splitter-cliffy.ts", [runId]);
  if (code !== 0) {
    if (code === 130) say("Cancelled.");
    else await reportFailedRuns();
  }
}

// Ask which upload path to use, then run the pusher on it.
async function uploadOrders(): Promise<void> {
  if (!(await wizardExists("pusher.ts"))) {
    say("Uploading orders is not available yet.");
    return;
  }
  const mode = await MepCLI.select({
    message: "Whose orders do you want to upload?" + selectHint(),
    choices: [
      { title: "Push my orders", value: "mine", description: "Pick a session you already split." },
      {
        title: "Push someone else's orders",
        value: "theirs",
        description: "Use a share link from this app.",
      },
    ],
  });
  if (mode === "mine") {
    await pushMine();
  } else {
    await pushTheirs();
  }
}

// Push one of my assigned runs, or a file I pick by hand.
async function pushMine(): Promise<void> {
  // Load assigned runs for the picker.
  const runs = (await listRuns()).filter((r) => r.status === "assigned");
  let target: string;
  if (runs.length === 0) {
    say("No assigned sessions found.");
    say("Pick Collect orders from platforms to start one.");
    target = await MepCLI.file({ message: "Pick your saved split", extensions: ["json"] });
  } else {
    const choice = await MepCLI.select({
      message: "Pick a session to push" + selectHint(),
      choices: [
        ...runs.map((r) => ({ title: r.id + " " + r.label, value: r.id })),
        { title: "Pick a saved split from this computer", value: "__file__" },
      ],
    });
    if (choice === "__file__") {
      target = await MepCLI.file({ message: "Pick your saved split", extensions: ["json"] });
    } else {
      target = choice;
    }
  }
  const code = await runWizard("pusher.ts", [target]);
  if (code !== 0) {
    if (code === 130) say("Cancelled.");
    else await reportFailedRuns();
  }
}

// Push orders from a share link or a file path.
async function pushTheirs(): Promise<void> {
  // Accept a link or a path in one prompt.
  const input = await MepCLI.text({ message: "Paste the share link:" });
  const trimmed = input.trim();
  if (trimmed.length === 0) {
    say("Nothing pasted. Try again when ready.");
    return;
  }
  let target = trimmed;
  // Fetch links over http and keep file paths as they are.
  if (trimmed.startsWith("http")) {
    let plaintext: string;
    try {
      plaintext = await fetchShareLink(trimmed);
    } catch (e) {
      // Keep the failing link in the log only.
      log.write(
        "warn",
        "share link fetch failed for " + trimmed + ": " +
          (e instanceof Error ? e.message : String(e)),
      );
      say("That link did not open. Check it and try again.");
      return;
    }
    // Store the import under the state root.
    const dir = stateRoot() + "/share/imports";
    await Deno.mkdir(dir, { recursive: true });
    target = dir + "/" + Date.now() + "-import.json";
    await Deno.writeTextFile(target, plaintext);
    log.write("info", "imported share link to " + target);
    say("Link opened. Starting the push flow.");
  }
  const code = await runWizard("pusher.ts", [target]);
  if (code !== 0) {
    if (code === 130) say("Cancelled.");
    else await reportFailedRuns();
  }
}

// Build one resume row title from a run record.
function shortDate(iso: string): string {
  // Show Sep 9 style. Add the year only for past years.
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return iso.slice(0, 10);
  const months = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ];
  const label = months[date.getMonth()] + " " + date.getDate();
  return date.getFullYear() === new Date().getFullYear()
    ? label
    : label + ", " + date.getFullYear();
}

// Build one resume row title from a run record.
function resumeTitle(run: RunMeta): string {
  // Keep the short date only.
  const date = shortDate(run.createdAt) || run.id;
  // Read optional progress counts when the run tracks them.
  const record = run as unknown as Record<string, unknown>;
  const done = record["ordersDone"];
  const total = record["ordersTotal"];
  // Show counts when both hold numbers.
  if (typeof done === "number" && typeof total === "number") {
    return "Split from " + date + " — " + done + " of " + total + " orders done";
  }
  if (run.status === "gathered") return "Split from " + date + " — not split yet";
  return "Split from " + date + " — " + run.status;
}

// Open a saved session and run its next step.
async function resumeMenu(): Promise<void> {
  // Load every live run newest first.
  const runs = await listRuns();
  if (runs.length === 0) {
    say("You have no saved sessions yet. Collect orders first to start one.");
    return;
  }
  const picked = await MepCLI.select({
    message: "Pick a session to continue" + selectHint(),
    choices: [
      ...runs.map((r) => ({
        title: resumeTitle(r),
        value: r.id,
        description: wrap(r.label + " · " + r.platforms.join(", ")),
      })),
      {
        title: "Back to the main menu",
        value: "__back__",
        description: "Return without changing anything.",
      },
    ],
  });
  if (picked === "__back__") return;
  const found = runs.find((r) => r.id === picked);
  if (found === undefined) {
    say("That session is gone. Pick another one.");
    return;
  }
  // Route each status to its next step.
  if (found.status === "gathered") {
    if (!(await wizardExists("splitter-cliffy.ts"))) {
      say("Assigning splits is not available yet.");
      return;
    }
    const code = await runWizard("splitter-cliffy.ts", [found.id]);
    if (code !== 0) {
      if (code === 130) say("Cancelled.");
      else await reportFailedRuns();
    }
    return;
  }
  if (found.status === "assigned") {
    if (!(await wizardExists("pusher.ts"))) {
      say("Uploading orders is not available yet.");
      return;
    }
    const code = await runWizard("pusher.ts", [found.id]);
    if (code !== 0) {
      if (code === 130) say("Cancelled.");
      else await reportFailedRuns();
    }
    return;
  }
  if (found.status === "failed") {
    log.write(
      "warn",
      "resume failed run " + found.id + ": " + (found.failureReason ?? "no reason recorded"),
    );
    say("That session failed.");
    say("Start over from Collect orders from platforms.");
    return;
  }
  say("That session already pushed. Nothing left to do.");
}

// True when the settings file misses. First run shows Start here.
async function settingsMissing(): Promise<boolean> {
  try {
    // Stat the file and treat any error as missing.
    await Deno.stat(stateRoot() + "/config/settings.json");
    return false;
  } catch {
    return true;
  }
}

// Run the settings wizard and report failures on the menu.
async function openSettings(): Promise<void> {
  const code = await runWizard("settings.ts", []);
  if (code !== 0) {
    if (code === 130) say("Cancelled.");
    else await reportFailedRuns();
  }
}

// Run first run onboarding: usage first, then currency, then setup.
async function startHere(): Promise<void> {
  // Ask how the user wants to use the app.
  const usage = await MepCLI.select({
    message: "How do you wish to use this app?" + selectHint(),
    choices: [
      {
        title: "With an AI helper",
        value: "ai",
        description: wrap("An AI assistant runs this app for you and handles the details."),
      },
      {
        title: "By myself but push to Splitwise automatically",
        value: "auto",
        description: wrap("Needs at least one person in your group to have Splitwise Pro."),
      },
      {
        title: "By myself, push manually",
        value: "manual",
        description: wrap(
          "You can use this program entirely for free. It writes one summary expense you can add to Splitwise quickly by hand.",
        ),
      },
    ],
  });
  // Save at once so a quit here still opens the full menu next time.
  const before = await loadSettings();
  await saveSettings({ currency: before.currency, usage });
  log.write("info", "onboarding saved usage " + usage);
  // Pick the currency label next through the shared picker.
  await pickCurrency(await loadSettings());
  if (usage === "ai") {
    // Show the AI setup prompt instead of the Splitwise question.
    printAiSetup(say);
  } else {
    // Offer the Splitwise setup right after the currency choice.
    const next = await MepCLI.select({
      message: "Set up Splitwise access now?" + selectHint(),
      choices: [
        { title: "Yes, set it up", value: "setup" },
        { title: "Skip for now — you can push without an account", value: "skip" },
      ],
    });
    if (next === "setup") {
      await setupSplitwise(log);
    } else {
      say("The summary mode needs no Splitwise account.");
    }
  }
  say("You are all set.");
}

// Guard one menu action and keep the wizard on the menu on failure.
async function guarded(log: RunLog, name: string, fn: () => Promise<void>): Promise<void> {
  try {
    await fn();
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    log.write("error", name + " failed: " + msg);
    warn("Action failed: " + msg);
    say("See the log at " + log.path);
  }
}

if (DRY) {
  await printDryPlan();
  wizardExit(0);
}

// Exit 1 only when the wizard itself cannot start.
let log: RunLog;
try {
  log = createRunLog("menu");
  log.write("info", "main menu started");
} catch (e) {
  console.error("Main menu cannot start: " + (e instanceof Error ? e.message : String(e)));
  wizardExit(1);
}

// First run lands straight on Start here with the full banner.
await banner("split-utils wizard v" + APP_VERSION, { stages: false });
// AGENT EDIT BELOW: replace example steps with real steps.
await createWizard<{ menu: string }>({ stages: false })
  .step(
    "menu",
    async () => {
      // Surface past failures before the first menu.
      await reportFailedRuns();
      let done = false;
      while (!done) {
        // Fresh screen each time so old menus never pile up.
        clearScreen();
        // Show Start here alone while the settings file misses.
        const firstRun = await settingsMissing();
        let choice: string;
        // Leave one blank line so the menu breathes.
        say("");
        if (firstRun) {
          choice = await MepCLI.select({
            message: "Pick a task" + selectHint(),
            choices: [
              {
                title: "Start here",
                value: "start",
                description: wrap("Answer three quick questions, then you are ready."),
              },
            ],
          });
        } else {
          choice = await MepCLI.select({
            message: "Pick a task" + selectHint(),
            choices: [
              {
                title: "Split and push recent orders",
                value: "flow",
                description: wrap(
                  "All three steps in order. Do this if you just want to sync some expenses.",
                ),
              },
              {
                title: "Pick up where you left off",
                value: "resume",
                description: "Continue a session you started earlier.",
              },
              {
                title: "Collect orders from platforms",
                value: "gather",
                description: wrap(
                  "Supported: Zepto, Blinkit, Zomato, Swiggy, or enter expenses by hand.",
                ),
              },
              {
                title: "Assign per-order split",
                value: "split",
                description: "Mark who each item belongs to, order by order.",
              },
              {
                title: "Upload orders to Splitwise",
                value: "upload",
                description: wrap(
                  "Send your split to Splitwise, or push a share link from a friend.",
                ),
              },
              menuSeparator("Setup"),
              {
                title: "Settings",
                value: "settings",
                description: "Currency, Splitwise access, and AI assistant.",
              },
              {
                title: "Set up with an AI assistant",
                value: "ai",
                description: wrap(
                  "Copies a message that sets up an AI assistant to run this app for you.",
                ),
              },
              menuSeparator(),
              { title: "Exit", value: "exit", description: "Close the app." },
            ],
          });
        }
        switch (choice) {
          case "start":
            await guarded(log, "start here", startHere);
            break;
          case "flow":
            await guarded(log, "whole flow", runWholeFlow);
            break;
          case "resume":
            await guarded(log, "resume", resumeMenu);
            break;
          case "gather":
            await guarded(log, "gather", gatherOrders);
            break;
          case "split":
            await guarded(log, "split", assignSplits);
            break;
          case "upload":
            await guarded(log, "upload", uploadOrders);
            break;
          case "settings":
            await guarded(log, "settings", openSettings);
            break;
          case "ai":
            printAiSetup(say);
            break;
          case "exit":
            done = true;
            break;
        }
      }
      return "done";
    },
  )
  .run();
log.close("main menu exit");
await finish();
