#!/usr/bin/env -S deno run --no-lock --allow-read --allow-write --allow-run --allow-env --allow-sys --allow-net
//
// A wizard walks a human through a manual procedure, step by step.
// Generated by the /wizard skill.
//
// Everything above the "STAGES" marker is the wizard library: do not hand-edit
// it. Author each stage below the marker as one named Pipeline step.
//
// Copy this file to the target path, replace the example steps, and run:
//   deno check <wizard>.ts
//   deno run --no-lock --allow-read --allow-write --allow-run --allow-env <wizard>.ts
//
// Self contained: pinned npm: imports resolve from the Deno cache.
// --no-lock keeps Deno from writing a deno.lock file. Nothing touches
// package.json, pnpm-lock.yaml, or node_modules.

import { MepCLI } from "mepcli";
import {
  APP_VERSION,
  banner,
  confirm,
  createWizard,
  finish,
  open_url,
  say,
  selectHint,
  setTotalStages,
  step,
  wizardExit,
} from "../src/wizardkit.ts";

// STAGES: AGENT EDIT BELOW. One Pipeline step per stage. Set TOTAL_STAGES to match.
// zx escape hatch: use $`cmd args` for shell, e.g. await $`gh auth status`.
setTotalStages(5);

import {
  buildAggregateSummary,
  buildItemizedComment,
  formatTitle,
  groupOrders,
  inferPayer,
  orderFingerprint,
  summariseOrder,
} from "../src/render.ts";
import { fmtRs, type OutputDoc, parseDate, type SplitEntry } from "../src/common.ts";
import { ISSUES_URL } from "../src/drift.ts";
import { createRunLog, type RunLog } from "../src/log.ts";
import { archiveRun, listRuns, readRun, runFilePath, stateRoot } from "../src/runstate.ts";
import { loadSettings } from "../src/settings.ts";
import {
  type AccessToken,
  loadCredentials,
  loadPushed,
  loadToken,
  parseVerifier,
  savePushed,
  saveToken,
  SplitwiseAPI,
} from "../src/splitwise.ts";

// One order groups split lines from one platform order.
type Order = SplitEntry[];

// Flag dry mode from the command line.
const DRY = Deno.args.includes("--dry") || Deno.args.includes("--dry-run");

// Active run log for the live path only.
let LOG: RunLog | null = null;

// First non flag argument feeds the source stage.
function positionalArg(): string | null {
  for (const arg of Deno.args) {
    if (!arg.startsWith("--")) return arg;
  }
  return null;
}

// True when the main menu owns this run.
const FROM_MENU = Deno.env.get("SPLIT_UTILS_FROM_MENU") === "1";

// Value of the back choice in every select prompt.
const BACK_VALUE = "__back_to_menu__";

// Build the back choice for a string valued select.
function backChoice(): { title: string; value: string } {
  // Offer one plain way back to the main menu.
  return { title: "Back to the main menu", value: BACK_VALUE };
}

// Exit cleanly when the user picked the back choice.
function checkBack(value: string): void {
  // Leave saved work in place and return to the menu.
  if (value === BACK_VALUE) wizardExit(0);
}

// Sum one order to rupees.
function orderTotal(order: Order): number {
  return order.reduce((sum, item) => sum + item.price, 0);
}

// Sum many orders to rupees.
function ordersTotalRs(orders: Order[]): number {
  return orders.reduce((sum, order) => sum + orderTotal(order), 0);
}

// Build today as YYYY-MM-DD in local time.
function todayLocal(): string {
  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return now.getFullYear() + "-" + pad(now.getMonth() + 1) + "-" + pad(now.getDate());
}

// Check the cutoff shape and confirm the date is real.
function validCutoff(value: string): boolean {
  const m = value.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!m) return false;
  const date = new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3]));
  return date.getFullYear() === Number(m[1]) &&
    date.getMonth() === Number(m[2]) - 1 &&
    date.getDate() === Number(m[3]);
}

// Return the first instant past the cutoff day.
function cutoffEnd(cutoff: string): number {
  const m = cutoff.match(/^(\d{4})-(\d{2})-(\d{2})$/)!;
  const date = new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3]));
  date.setDate(date.getDate() + 1);
  return date.getTime();
}

// Read the display name from a Splitwise user record.
function fullName(user: Record<string, unknown>): string {
  const first = String(user.first_name ?? "");
  const last = String(user.last_name ?? "");
  return (first + " " + last).trim();
}

// Read the first name from a Splitwise user record.
function firstName(user: Record<string, unknown>): string {
  return String(user.first_name ?? "");
}

// Read the numeric id from a Splitwise user record.
function userId(user: Record<string, unknown>): number {
  return Number(user.id);
}

// Append one user to a name lookup list.
function pushTo(
  map: Map<string, Record<string, unknown>[]>,
  key: string,
  user: Record<string, unknown>,
): void {
  const list = map.get(key) ?? [];
  list.push(user);
  map.set(key, list);
}

// Ask for a Splitwise id by hand.
async function askUserId(person: string): Promise<number> {
  const raw = await MepCLI.text({
    message: "Type the number next to " + person + " in the Splitwise member list:",
  });
  return Number(raw.trim());
}

// Cache a fresh token beside the consumer key.
// Delegates to saveToken so the write lands with owner-only rights.
async function saveFreshToken(token: AccessToken, key: string, secret: string): Promise<void> {
  await saveToken(token, key, secret);
}

// Map each local person to a Splitwise user id.
async function buildNameMap(api: SplitwiseAPI, people: string[]): Promise<Map<string, number>> {
  const me = await api.getCurrentUser();
  const friends = await api.getFriends();
  const all: Record<string, unknown>[] = [me, ...friends];
  const byFull = new Map<string, Record<string, unknown>[]>();
  const byFirst = new Map<string, Record<string, unknown>[]>();
  for (const user of all) {
    pushTo(byFull, fullName(user), user);
    pushTo(byFirst, firstName(user), user);
  }
  const out = new Map<string, number>();
  for (const person of people) {
    const fullHit = byFull.get(person) ?? [];
    if (fullHit.length === 1) {
      const id = userId(fullHit[0]);
      out.set(person, id);
      say(person + " maps to Splitwise id " + id + ".");
      continue;
    }
    const first = person.split(/\s+/)[0];
    const firstHit = byFirst.get(first) ?? [];
    if (firstHit.length === 1) {
      const id = userId(firstHit[0]);
      out.set(person, id);
      say(person + " maps to Splitwise id " + id + " by first name.");
      continue;
    }
    if (firstHit.length > 1) {
      say("More than one Splitwise member matches " + person + ". Pick one:");
      const picked = await MepCLI.select<number>({
        message: "Pick the user for " + person + ":" + selectHint(),
        choices: [
          ...firstHit.map((user) => ({
            title: fullName(user) + " (id " + userId(user) + ")",
            value: userId(user),
          })),
          { title: "Type an id by hand", value: -1 },
          { title: "Back to the main menu", value: -2 },
        ],
      });
      if (picked === -2) {
        wizardExit(0);
      }
      if (picked === -1) {
        out.set(person, await askUserId(person));
      } else {
        out.set(person, picked);
        say(person + " maps to Splitwise id " + picked + ".");
      }
      continue;
    }
    say(
      "No Splitwise member matches " + person +
        " yet. Add them in Splitwise first, then come back.",
    );
    out.set(person, await askUserId(person));
  }
  return out;
}

// Push one order with the Python parameter set and save the fingerprint.
async function pushOneOrder(
  api: SplitwiseAPI,
  order: Order,
  people: string[],
  nameMap: Map<string, number>,
  payer: string,
  groupId: number,
  currency: string,
): Promise<string | null> {
  const total = orderTotal(order);
  const owed = new Map<string, number>();
  for (const item of order) {
    for (const [name, amount] of Object.entries(item.assignments)) {
      owed.set(name, (owed.get(name) ?? 0) + amount);
    }
  }
  const data: Record<string, string> = {
    cost: fmtRs(total),
    description: formatTitle(order, currency + " "),
    group_id: String(groupId),
    currency_code: currency,
  };
  people.forEach((person, i) => {
    data[`users__${i}__user_id`] = String(nameMap.get(person));
    data[`users__${i}__paid_share`] = person === payer ? fmtRs(total) : "0.00";
    data[`users__${i}__owed_share`] = fmtRs(owed.get(person) ?? 0);
  });
  const result = await api.createExpense(data);
  const eid = result.expenses?.[0]?.id;
  if (eid === undefined || eid === null) return null;
  await api.createComment(eid, buildItemizedComment(order, people));
  const merged = await loadPushed();
  merged[orderFingerprint(order)] = eid;
  await savePushed(merged);
  return String(eid);
}

// Log a Splitwise error and stop without retry.
function failPush(err: unknown, fingerprint: string): never {
  const msg = err instanceof Error ? err.message : String(err);
  LOG?.write("error", "push failed for " + fingerprint + ": " + msg);
  LOG?.close("push failed");
  say("Splitwise call failed: " + msg + ".");
  say("The fingerprint was NOT saved. Check Splitwise before you rerun.");
  say("The run log holds the details.");
  say("Report the problem at " + ISSUES_URL + ".");
  wizardExit(1);
  throw new Error("unreachable");
}

// Source file plus run id feed every later stage.
interface SourceResult {
  file: string;
  runId: string | null;
  people: string[];
  splits: SplitEntry[];
  settlements: OutputDoc["settlements"];
}

// Login state plus push targets feed the push stage.
interface SplitwiseResult {
  api: SplitwiseAPI | null;
  nameMap: Map<string, number>;
  groupId: number;
  currency: string;
  aggregate: boolean;
}

// Kept order groups plus the payer feed confirm and push.
interface CutoffResult {
  cutoff: string;
  groups: Order[];
  dropped: number;
  payer: string;
}

// Confirmed groups plus skip counts feed the push stage.
interface ConfirmResult {
  confirmed: Order[];
  skipped: number;
  stopped: boolean;
}

// Final counts close the run.
interface PushResult {
  pushedCount: number;
  skipped: number;
  totalRs: number;
}

// Wizard context carries one result per stage in run order.
interface PushCtx extends Record<string, unknown> {
  source: SourceResult;
  splitwise: SplitwiseResult;
  cutoff: CutoffResult;
  confirm: ConfirmResult;
  push: PushResult;
}

if (!DRY) {
  await banner("split-utils wizard v" + APP_VERSION + " — push orders");
}
await createWizard<PushCtx>()
  .step(
    "source",
    async () => {
      const arg = positionalArg();
      let file: string | null = null;
      let runId: string | null = null;
      if (arg) {
        try {
          const info = await Deno.stat(arg);
          if (info.isFile && arg.endsWith(".json")) file = arg;
        } catch {
          // Fall through to the run lookup below.
        }
        if (!file) {
          const found = await readRun(arg);
          const path = found && await runFilePath(arg, found.meta.outputFile ?? "output.json");
          if (found && path) {
            file = path;
            runId = arg;
          }
        }
      }
      if (!file) {
        const runs = (await listRuns()).filter((run) => run.status === "assigned");
        if (runs.length === 0) {
          say("No assigned runs found. Gather and assign first.");
          wizardExit(1);
        }
        const picked = await MepCLI.select<string>({
          message: "Pick an assigned run to push:" + selectHint(),
          choices: [
            ...runs.map((run) => ({
              title: run.id + " (" + run.platforms.join("+") + ")",
              value: run.id,
            })),
            backChoice(),
          ],
        });
        checkBack(picked);
        runId = picked;
        const found = await readRun(runId);
        const path = found && await runFilePath(runId, found.meta.outputFile ?? "output.json");
        if (!found || !path) {
          say("Run output file is missing.");
          say("Pick up where you left off from the main menu to continue it.");
          wizardExit(1);
        }
        file = path;
      }
      const doc = JSON.parse(await Deno.readTextFile(file)) as OutputDoc;
      if (!doc.people || !doc.splits) {
        say("Source file lacks people or splits.");
        say("Pick Collect orders from platforms from the main menu to start over.");
        wizardExit(1);
      }
      if (!DRY) {
        LOG = createRunLog("push");
        LOG.write("info", "push started for " + file);
      }
      say("Found your split. Ready to continue.");
      if (runId) LOG?.write("info", "run id " + runId);
      const result: SourceResult = {
        file,
        runId,
        people: doc.people,
        splits: doc.splits,
        settlements: doc.settlements ?? [],
      };
      return result;
    },
  )
  .step(
    "splitwise",
    async (ctx) => {
      if (DRY) {
        say("Dry mode skips the Splitwise login.");
        // Read the saved code so dry output uses the same label.
        const stored = await loadSettings();
        const dry: SplitwiseResult = {
          api: null,
          nameMap: new Map(),
          groupId: 0,
          currency: stored.currency,
          aggregate: false,
        };
        return dry;
      }
      const statePath = stateRoot() + "/config/splitwise.env";
      let envPath: string | null = null;
      try {
        const info = await Deno.stat(statePath);
        if (info.isFile) envPath = statePath;
      } catch {
        // Fall through to the env var below.
      }
      if (!envPath) {
        const override = Deno.env.get("SPLITWISE_ENV");
        if (override) envPath = override;
      }
      if (!envPath) {
        // Offer one summary file when Splitwise access is missing.
        const fallback = await MepCLI.select<string>({
          message: "No Splitwise access is configured." + selectHint(),
          choices: [
            {
              title: "Write one short summary instead. No Splitwise login needed.",
              value: "aggregate",
            },
            { title: "Stop — set up Splitwise access first", value: "stop" },
            backChoice(),
          ],
        });
        checkBack(fallback);
        if (fallback === "aggregate") {
          // Read the saved code so the summary uses the same label.
          const stored = await loadSettings();
          const single: SplitwiseResult = {
            api: null,
            nameMap: new Map(),
            groupId: 0,
            currency: stored.currency,
            aggregate: true,
          };
          return single;
        }
        say("Open Settings from the main menu and pick Set up Splitwise access.");
        wizardExit(0);
      }
      const creds = await loadCredentials(envPath);
      let api = new SplitwiseAPI({
        consumerKey: creds.consumerKey,
        consumerSecret: creds.consumerSecret,
      });
      const cached = await loadToken();
      if (cached) {
        api = new SplitwiseAPI(
          { consumerKey: creds.consumerKey, consumerSecret: creds.consumerSecret },
          cached,
        );
      } else {
        const { url, requestToken } = await api.getAuthorizeUrl();
        say("Approve access in the browser window.");
        await open_url(url);
        step("Approve the app in the browser.");
        step("Copy the verifier code from the page.");
        const raw = await MepCLI.text({ message: "Paste the verifier code:" });
        const token = await api.getAccessToken(requestToken, parseVerifier(raw));
        await saveFreshToken(token, creds.consumerKey, creds.consumerSecret);
        api = new SplitwiseAPI(
          { consumerKey: creds.consumerKey, consumerSecret: creds.consumerSecret },
          token,
        );
      }
      const me = await api.getCurrentUser();
      say("Signed in as " + fullName(me) + ".");
      say("Match local people to Splitwise users.");
      const nameMap = await buildNameMap(api, ctx.source.people);
      say("Pick the Splitwise group for the new expenses.");
      const groups = await api.getGroups();
      const groupId = await MepCLI.select<number>({
        message: "Push into which group?" + selectHint(),
        choices: [
          { title: "No group (plain expense)", value: 0 },
          ...groups.map((group) => ({
            title: String(group.name ?? "group") + " (id " + String(group.id) + ")",
            value: Number(group.id),
          })),
          { title: "Back to the main menu", value: -2 },
        ],
      });
      if (groupId === -2) {
        wizardExit(0);
      }
      // Read the saved code from settings.
      const stored = await loadSettings();
      const currency = stored.currency;
      say("Currency in use is " + currency + ".");
      say("Push target uses group " + groupId + " and currency " + currency + ".");
      const result: SplitwiseResult = { api, nameMap, groupId, currency, aggregate: false };
      return result;
    },
  )
  .step(
    "cutoff",
    async (ctx) => {
      const groups = groupOrders(ctx.source.splits);
      if (groups.length === 0) {
        say("No orders found in the source file.");
        wizardExit(1);
      }
      const payer = inferPayer(groups[0], ctx.source.settlements);
      // Offer a way back before the date prompt on menu runs.
      if (FROM_MENU && !DRY) {
        const go = await MepCLI.select<string>({
          message: "Pick the last date to include" + selectHint(),
          choices: [
            { title: "Type a date", value: "go" },
            backChoice(),
          ],
        });
        checkBack(go);
      }
      let cutoff: string;
      if (DRY) {
        cutoff = todayLocal();
        say("Test mode uses today as the last date: " + cutoff + ".");
      } else {
        cutoff = await MepCLI.text({
          message: "Include orders up to which date (YYYY-MM-DD)?",
          initial: todayLocal(),
          validate: (value) => validCutoff(value) ? true : "Use the form YYYY-MM-DD.",
        });
      }
      const end = cutoffEnd(cutoff);
      const kept: Order[] = [];
      let dropped = 0;
      for (const order of groups) {
        const date = parseDate(order[0].date);
        if (date && date.getTime() >= end) {
          dropped += 1;
          continue;
        }
        kept.push(order);
      }
      say("Last date kept: " + cutoff + ". Skipped " + dropped + " later orders.");
      LOG?.write("info", "cutoff " + cutoff + " kept " + kept.length + " dropped " + dropped);
      const result: CutoffResult = { cutoff, groups: kept, dropped, payer };
      return result;
    },
  )
  .step(
    "confirm",
    async (ctx) => {
      const people = ctx.source.people;
      const payer = ctx.cutoff.payer;
      const groups = ctx.cutoff.groups;
      const pushed = await loadPushed();
      const confirmed: Order[] = [];
      let skipped = 0;
      let stopped = false;
      if (ctx.splitwise.aggregate) {
        // Keep only groups the API never pushed.
        const remaining = groups.filter((order) => !Object.hasOwn(pushed, orderFingerprint(order)));
        skipped = groups.length - remaining.length;
        say("Excluded " + skipped + " orders already pushed through the API.");
        console.log(
          buildAggregateSummary(
            remaining,
            people,
            payer,
            ctx.source.settlements,
            ctx.splitwise.currency + " ",
          ),
        );
        const write = await confirm("Save this summary to share with your group?");
        if (write) {
          confirmed.push(...remaining);
        } else {
          stopped = true;
        }
        LOG?.write("info", "confirmed " + confirmed.length + " skipped " + skipped);
        const single: ConfirmResult = { confirmed, skipped, stopped };
        return single;
      }
      for (let i = 0; i < groups.length; i++) {
        const order = groups[i];
        const fingerprint = orderFingerprint(order);
        const known = Object.hasOwn(pushed, fingerprint);
        if (DRY) {
          console.log(
            summariseOrder(order, people, payer, i, groups.length, ctx.splitwise.currency + " "),
          );
          console.log(buildItemizedComment(order, people));
          LOG?.write("info", "order fingerprint " + fingerprint);
          if (known) {
            LOG?.write("info", "already pushed as expense " + pushed[fingerprint]);
            say("Already sent to Splitwise. Nothing to do.");
            skipped += 1;
          } else {
            say("This order would push.");
            confirmed.push(order);
          }
          continue;
        }
        if (known) {
          LOG?.write("info", "already pushed as expense " + pushed[fingerprint] + ", skipping");
          say("Already sent to Splitwise. Nothing to do.");
          skipped += 1;
          continue;
        }
        console.log(
          summariseOrder(order, people, payer, i, groups.length, ctx.splitwise.currency + " "),
        );
        console.log(buildItemizedComment(order, people));
        LOG?.write("info", "order fingerprint " + fingerprint);
        const choice = await MepCLI.select<string>({
          message: "Push this order to Splitwise?" + selectHint(),
          choices: [
            { title: "Push this expense", value: "push" },
            { title: "Skip this one", value: "skip" },
            { title: "Stop here", value: "stop" },
            backChoice(),
          ],
        });
        checkBack(choice);
        if (choice === "push") {
          confirmed.push(order);
        } else if (choice === "skip") {
          skipped += 1;
        } else {
          stopped = true;
          skipped += groups.length - i;
          break;
        }
      }
      LOG?.write("info", "confirmed " + confirmed.length + " skipped " + skipped);
      const result: ConfirmResult = { confirmed, skipped, stopped };
      return result;
    },
  )
  .step(
    "push",
    async (ctx) => {
      const done = ctx.confirm;
      if (DRY) {
        const total = ordersTotalRs(done.confirmed);
        say("Test mode ends here. Nothing went to Splitwise.");
        say("Orders that would push: " + done.confirmed.length + ".");
        say("Skipped orders: " + done.skipped + ".");
        say("Total rupees that would push: " + fmtRs(total) + ".");
        await finish(false);
        wizardExit(0);
      }
      if (ctx.splitwise.aggregate) {
        const included = done.confirmed;
        if (included.length > 0) {
          // Rebuild the block from the confirmed groups.
          const block = buildAggregateSummary(
            included,
            ctx.source.people,
            ctx.cutoff.payer,
            ctx.source.settlements,
            ctx.splitwise.currency + " ",
          );
          // Place the file next to the source file.
          const dir = ctx.source.file.includes("/")
            ? ctx.source.file.slice(0, ctx.source.file.lastIndexOf("/"))
            : ".";
          const stamp = Math.floor(Date.now() / 1000);
          const path = dir + "/aggregate-" + stamp + ".txt";
          await Deno.writeTextFile(path, block + "\n");
          say("Saved your expense summary.");
          LOG?.write("info", "wrote " + path);
        }
        const total = ordersTotalRs(included);
        say("Orders included: " + included.length + ".");
        say("Skipped orders: " + done.skipped + ".");
        say("Total rupees: " + fmtRs(total) + ".");
        await finish();
        wizardExit(0);
      }
      const api = ctx.splitwise.api;
      if (!api) {
        say("Splitwise login is missing.");
        wizardExit(1);
      }
      let pushedCount = 0;
      for (const order of done.confirmed) {
        const fingerprint = orderFingerprint(order);
        try {
          const eid = await pushOneOrder(
            api,
            order,
            ctx.source.people,
            ctx.splitwise.nameMap,
            ctx.cutoff.payer,
            ctx.splitwise.groupId,
            ctx.splitwise.currency,
          );
          if (eid === null) {
            say("Splitwise gave no expense id. The fingerprint stays unsaved.");
          } else {
            LOG?.write("info", "pushed expense id " + eid);
            say("Sent to Splitwise.");
          }
          pushedCount += 1;
        } catch (err) {
          failPush(err, fingerprint);
        }
      }
      if (ctx.source.runId && !done.stopped) {
        await archiveRun(ctx.source.runId);
        say("Archived run " + ctx.source.runId + ".");
      }
      if (ctx.source.runId && done.stopped) {
        say("Left the run in place. The run stopped early.");
      }
      const totalRs = ordersTotalRs(done.confirmed);
      say("Pushed " + pushedCount + " expense(s), skipped " + done.skipped + ".");
      say("Total rupees pushed: " + fmtRs(totalRs) + ".");
      LOG?.close("pushed " + pushedCount + " skipped " + done.skipped);
      await finish();
      const result: PushResult = { pushedCount, skipped: done.skipped, totalRs };
      return result;
    },
  )
  .run();
