#!/usr/bin/env -S deno run --no-lock --allow-read --allow-write --allow-run --allow-env --allow-sys --allow-net
//
// A wizard walks a human through a manual procedure, step by step.
// Generated by the /wizard skill.
//
// Everything above the "STAGES" marker is the wizard library: do not hand-edit
// it. Author each stage below the marker as one named Pipeline step.
//

import { MepCLI } from "mepcli";
import {
  APP_VERSION,
  banner,
  finish,
  say,
  selectHint,
  setTotalStages,
  wizardExit,
} from "../src/wizardkit.ts";
import { loadSettings, pickCurrency } from "../src/settings.ts";
import { setupSplitwise, splitwiseConfigured } from "../src/splitwise-setup.ts";
import { printAiSetup } from "../src/ai-setup.ts";
import { createRunLog } from "../src/log.ts";

// STAGES: AGENT EDIT BELOW. One Pipeline step per stage. Set TOTAL_STAGES to match.
setTotalStages(1);

await banner("split-utils wizard v" + APP_VERSION + " — settings");

const log = createRunLog("settings");

let open = true;
while (open) {
  const saved = await loadSettings();
  const hasKey = await splitwiseConfigured();
  // Leave one blank line so the menu breathes.
  say("");
  const picked = await MepCLI.select<string>({
    message: "What do you want to change?" + selectHint(),
    choices: [
      {
        title: "Currency",
        value: "currency",
        description: "Shown next to every amount. Today it is " + saved.currency + ".",
      },
      hasKey
        ? {
          title: "Change Splitwise access",
          value: "splitwise",
          description: "Replace the saved Consumer Key and Consumer Secret.",
        }
        : {
          title: "Set up Splitwise access",
          value: "splitwise",
          description: "Connect your account so the app can push expenses for you.",
        },
      {
        title: "Connect an AI assistant",
        value: "ai",
        description: "Copies a message that sets up an AI assistant to run this app for you.",
      },
      { title: "Back to the main menu", value: "back" },
    ],
  });
  if (picked === "currency") {
    // Save and confirm through the shared picker.
    const next = await pickCurrency(saved);
    say("Saved currency " + next.currency + ".");
  } else if (picked === "splitwise") {
    await setupSplitwise(log);
  } else if (picked === "ai") {
    printAiSetup(say);
  } else {
    open = false;
  }
}
await finish();
wizardExit(0);
