#!/usr/bin/env bash
# dsh personal bundle installer — idempotent.
#
# Usage:  clone the dotfiles-ai repo, cd into it, run ./dsh/sync.sh
#   ./dsh/sync.sh                 # installs into $DSH_HOME (default ~/.dsh)
#   DSH_HOME=/path/to/home ./dsh/sync.sh
#   AIDOS_BUNDLE_PATH=/path  ./dsh/sync.sh   # where the aidos package lives
#
# What it does:
#   1. pnpm install (repo dev deps, e.g. esbuild for the build step)
#   2. build the personal plugins (bash-guard, see, manifest-guard,
#      package-tool, session-hygiene) to self-contained ESM bundles
#   3. copy the ported skills into $DSH_HOME/skills
#   4. copy AGENTS.md into $DSH_HOME/AGENTS.md
#   5. copy the dsh-better-edit personal-preset guidance overrides
#      into $DSH_HOME/plugins/dsh-better-edit/
#   6. copy the bash-guard rule drop-ins into $DSH_HOME/plugins/guards/
#   7. write the web-profile patch (cordis.patch.yml): the host-plane rows
#      that apply to EVERY preset: the four MCP servers, the bash guard
#      (git/find/grep deny rules from the drop-in files), the manifest
#      guard, the package tool, and the see vision helper
#   8. register the aidos agent preset in $DSH_HOME/.agent-presets/aidos
#      (real directory, loader re-exporting the aidos bundle that lives at
#      AIDOS_BUNDLE_PATH, defaulting to $HOME/repos/aidos/packages/aidos), and
#      add that bundle to the web profile's dsh.profile.bundles so the
#      host-plane aidos-core service mounts (see step 8b below)
#   9. set the agent-presets default to `standard`, and declare image input on
#      the meridian route so the see tool's vision subagent can read images
#  10. ensure .dsh_better_edit/ is ignored by git machine-wide (core.excludesFile
#      if set, else git's XDG default) so the hashline artifact is never tracked
#
# Idempotent: re-running it converges to the same state. Safe to run after
# clone, after a rebase, or after editing the bundle source.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
export DSH_HOME="${DSH_HOME:-$HOME/.dsh}"
AIDOS_BUNDLE_PATH="${AIDOS_BUNDLE_PATH:-$REPO/../aidos/packages/aidos}"

echo "=== [1/8] Install repo dev deps (esbuild for the build step)"
(cd "$REPO" && pnpm install)

echo "=== [2/8] Build the personal plugins"
(cd "$HERE" && node build.mjs)

echo "=== [3/8] Sync skills -> $DSH_HOME/skills"
mkdir -p "$DSH_HOME/skills"
cp -r "$HERE/skills/." "$DSH_HOME/skills/"

echo "=== [4/8] Sync AGENTS.md -> $DSH_HOME/AGENTS.md"
cp "$HERE/home/AGENTS.md" "$DSH_HOME/AGENTS.md"

echo "=== [5/8] Sync dsh-better-edit guidance overrides"
mkdir -p "$DSH_HOME/plugins/dsh-better-edit"
cp -r "$HERE/home/plugins/dsh-better-edit/." "$DSH_HOME/plugins/dsh-better-edit/"

echo "=== [6/9] Sync bash-guard rule drop-ins (git, find, grep) -> $DSH_HOME/plugins/guards"
mkdir -p "$DSH_HOME/plugins/guards"
cp -r "$HERE/guards/." "$DSH_HOME/plugins/guards/"

echo "=== [7/9] Write the web-profile patch (host-plane rows, applies to every preset)"
patch_dir="$DSH_HOME/profiles/web"
mkdir -p "$patch_dir"
cat > "$patch_dir/cordis.patch.yml" <<PATCH
# Auto-generated by $HERE/sync.sh. Do not hand-edit; re-run the script instead.
# Personal bundle host-plane rows: these apply to EVERY session regardless of
# preset — the MCP servers, the bash guard (rules read live from
# $DSH_HOME/plugins/guards/*.json), the manifest guard, the package tool,
# and the profile-routed see vision helper. The plugin files resolve their
# @deepseek-ai/* imports against the host base (dsh install node_modules);
# unbash + the walker are bundled inside each plugin file.
- insert:
    - id: mcp-nostrbook
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: nostrbook
        transport: stdio
        command: npx
        args: ['-y', '@nostrbook/mcp@latest']
    - id: mcp-gitlab
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: gitlab
        transport: stdio
        command: glab
        args: ['mcp', 'serve']
    - id: mcp-swiggy-food
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: swiggy-food
        transport: streamable-http
        url: https://mcp.swiggy.com/food
    - id: mcp-swiggy-instamart
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: swiggy-instamart
        transport: streamable-http
        url: https://mcp.swiggy.com/im
    - id: mcp-git
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: git
        transport: stdio
        command: uvx
        args: ['mcp-server-git']
    - id: bash-guard
      name: $HERE/plugins/bash-guard.js
      config:
        guardsDir: $DSH_HOME/plugins/guards
    - id: manifest-guard
      name: $HERE/plugins/manifest-guard.js
    - id: package-tool
      name: $HERE/plugins/package-tool.js
    - id: see
      name: $HERE/plugins/see.js
PATCH

echo "=== [8/9] Register the aidos agent preset"
mkdir -p "$DSH_HOME/.agent-presets/aidos"
cat > "$DSH_HOME/.agent-presets/aidos/agent.cordis.yml" <<'EOF'
# The aidos agent preset composition (installed by $REPO/dsh/sync.sh).
# The loader re-exports the real plugin bundle from the aidos package, so the
# plugin's @deepseek-ai/* imports resolve from the bundle's node_modules.
- name: ./aidos-loader.js
EOF
if [ -f "$AIDOS_BUNDLE_PATH/presets/aidos/aidos-tools.js" ]; then
  cat > "$DSH_HOME/.agent-presets/aidos/aidos-loader.js" <<EOF
// Installed by $REPO/dsh/sync.sh. Re-exports the real aidos-tools plugin bundle.
export { name, inject, Config, apply } from "$AIDOS_BUNDLE_PATH/presets/aidos/aidos-tools.js";
EOF
else
  echo "WARNING: aidos bundle not found at $AIDOS_BUNDLE_PATH. Skipping the loader;"
  echo "         preset $DSH_HOME/.agent-presets/aidos will be listed as broken."
  echo "         Set AIDOS_BUNDLE_PATH to the aidos package and re-run."
  rm -f "$DSH_HOME/.agent-presets/aidos/aidos-loader.js"
fi
cat > "$DSH_HOME/.agent-presets/aidos/preset.yml" <<'EOF'
name: Aidos
description: "The ticket board agent: plan, tickets, evidence, and state-gated tool access."
order: 3
EOF

echo "=== [8b] Add aidos as a web-profile bundle (mounts host-plane aidos-core)"
# The aidos preset's tools run against a host-plane `aidos` core service that
# the aidos BUNDLE patch mounts (aidos-invariants + aidos-core). The web-profile
# patch file cannot resolve those rows with a bare 'name:', so add the package
# to dsh.profile.bundles (the container-verified path). Idempotent: dsh's
# reconcile excludes a bundle already present.
if command -v dsh >/dev/null 2>&1; then
  dsh plugin --profile web add "$AIDOS_BUNDLE_PATH"
else
  echo "WARNING: dsh not on PATH; skipping aidos bundle-add."
  echo "         Re-run './dsh/sync.sh' from a shell where dsh is installed."
fi

echo "=== [9/9] Set agent-presets default + meridian image input"
python3 - "$DSH_HOME/settings.yaml" <<'PY'
import sys
import yaml
p = sys.argv[1]
d = yaml.safe_load(open(p)) or {}
d.setdefault('agent-presets', {})['default'] = 'standard'
# meridian reports image_input.supported true for all its models, but dsh's
# pi-ai adapter only accepts images when a route/model declares image input.
# Hand-declared models get none by default, so the see tool's vision subagent
# fails. Declare it once on the route for every meridian model.
meridian = d.setdefault('llm-pi-ai', {}).setdefault('providers', {}).setdefault('meridian', {})
meridian['defaultInput'] = ['text', 'image']
with open(p, 'w') as f:
    yaml.safe_dump(d, f, sort_keys=False)
print(open(p).read())
PY

echo "=== [9b] Ensure .dsh_better_edit/ is ignored by git machine-wide"
# The hashline editor drops a .dsh_better_edit/ state directory into whatever
# repo a session edits files in. It is a tool artifact that belongs in no
# repository, so ignore it once per machine rather than per repo. Honor an
# existing core.excludesFile; otherwise use git's XDG default path, which git
# reads with no extra configuration when core.excludesFile is unset.
git_ignore=""
if command -v git >/dev/null 2>&1; then
  git_ignore="$(git config --get core.excludesFile || true)"
fi
if [ -n "$git_ignore" ]; then
  git_ignore="${git_ignore/#\~/$HOME}"
else
  git_ignore="${XDG_CONFIG_HOME:-$HOME/.config}/git/ignore"
fi
mkdir -p "$(dirname "$git_ignore")"
touch "$git_ignore"
if grep -qxF '.dsh_better_edit/' "$git_ignore"; then
  echo "    already ignored in $git_ignore"
else
  cat >> "$git_ignore" <<'EOF'

# dsh-better-edit (hashline) scratch/state directory. A tool artifact that
# appears in whatever repo a session edits files in. Never belongs in a repo.
.dsh_better_edit/
EOF
  echo "    added .dsh_better_edit/ to $git_ignore"
fi

echo
echo "Done. Restart dsh web to pick up the new bundle layer (bundle rows are"
echo "static per boot; skills/presets are discovered live on the next session)."
echo
echo "Installed:"
echo "  skills:  $DSH_HOME/skills"
echo "  rules:   $DSH_HOME/AGENTS.md"
echo "  guards:  $DSH_HOME/plugins/guards"
echo "  patch:   $DSH_HOME/profiles/web/cordis.patch.yml"
echo "  preset:  $DSH_HOME/.agent-presets/aidos"
echo "  ignore:  $git_ignore (.dsh_better_edit/)"